/*

backwards_fks.sql

The "create index" statements in this script create indexes on columns which
have foreign keys, to solve a problem we'd been having in which deletes from the
referenced tables were slow. To clarify, here's an example: There's a foreign
key from dots.AaSequenceImp.taxon_id to sres.taxon.taxon_id. (That makes sense;
you wouldn't want a value in AaSequence.taxon_id unless it already exists as the
taxon_id of some row in sres.Taxon.) But there was no index on
AaSequenceImp.taxon_id. So before Oracle could delete a row from sres.taxon, it
had to do a full table scan of dots.AaSequenceImp.

We created these "create index" statements with the following SQL, which
queries all_constraints/all_cons_columns for columns that have foreign-key
constraints, and MINUSes those that are already indexed.

Note that all this assumes a database in which foreign keys and primary keys are
single columns. That's true for GUS; it isn't true in general of Oracle databases.

select distinct 'create index ' || acc.owner || '.' || substr(acc.table_name, 1, 23) || '_revix' || mod(rownum, 10) ||' on '
       || acc.owner || '.' || acc.table_name || ' (' || acc.column_name || ', ' || nvl(pks.column_name, '??PK??') || ') tablespace indx;'
from all_cons_columns acc, all_constraints ac,
     (select accp.owner || '.' || accp.table_name as tab, accp.column_name
      from all_constraints acp, all_cons_columns accp
      where acp.constraint_name = accp.constraint_name
        and constraint_type = 'P') pks
where ac.constraint_name = acc.constraint_name
  and ac.constraint_type = 'R'
  and acc.position = 1
  and acc.owner || '.' || acc.table_name = pks.tab(+)
  and acc.owner not in ('SYS', 'SYSTEM', 'SYSMAN', 'PERFSTAT', 'OLAPSYS', 'MDSYS', 'EXFSYS', 'SCOTT', 'DBSNMP')
  and acc.owner || '.' || acc.table_name || '.' || acc.column_name
      not in (select table_owner || '.' || table_name || '.' || column_name
              from all_ind_columns
              where column_position = 1)
order by 'create index ' || acc.owner || '.' || substr(acc.table_name, 1, 23) || '_revix' || mod(rownum, 10) ||' on '
       || acc.owner || '.' || acc.table_name || ' (' || acc.column_name || ', ' || nvl(pks.column_name, '??PK??') || ') tablespace indx;';
*/

create index CORE.ANALYSISALGORITHM_revix6 on CORE.ANALYSISALGORITHM (ALGORITHM_INVOCATION_ID, ANALYSIS_ALGORITHM_ID) tablespace indx;
create index CORE.ANALYSISALGORITHM_revix7 on CORE.ANALYSISALGORITHM (TABLE_ID, ANALYSIS_ALGORITHM_ID) tablespace indx;
create index DOTS.AAFEATURECOMMENT_revix9 on DOTS.AAFEATURECOMMENT (COMMENT_NAME_ID, AA_FEATURE_COMMENT_ID) tablespace indx;
create index DOTS.AAFEATUREDBREF_revix0 on DOTS.AAFEATUREDBREF (DB_REF_ID, AA_FEATURE_DB_REF_ID) tablespace indx;
create index DOTS.AAFEATUREDBREF_revix1 on DOTS.AAFEATUREDBREF (AA_FEATURE_ID, AA_FEATURE_DB_REF_ID) tablespace indx;
create index DOTS.AASEQUENCEENZYMECLASS_revix3 on DOTS.AASEQUENCEENZYMECLASS (EC_ASSIGNMENT_CONTACT_ID, AA_SEQUENCE_ENZYME_CLASS_ID) tablespace indx;
create index DOTS.AASEQUENCEENZYMECLASS_revix4 on DOTS.AASEQUENCEENZYMECLASS (ENZYME_CLASS_ID, AA_SEQUENCE_ENZYME_CLASS_ID) tablespace indx;
create index DOTS.AASEQUENCEIMP_revix6 on DOTS.AASEQUENCEIMP (TAXON_ID, AA_SEQUENCE_ID) tablespace indx;
create index DOTS.AASEQUENCEIMP_revix7 on DOTS.AASEQUENCEIMP (SEQUENCE_ONTOLOGY_ID, AA_SEQUENCE_ID) tablespace indx;
create index DOTS.AASEQUENCEIMP_revix8 on DOTS.AASEQUENCEIMP (SEQUENCE_TYPE_ID, AA_SEQUENCE_ID) tablespace indx;
create index DOTS.BLATALIGNMENT_revix0 on DOTS.BLATALIGNMENT (BLAT_ALIGNMENT_QUALITY_ID, BLAT_ALIGNMENT_ID) tablespace indx;
create index DOTS.DEVSTAGELIBRARY_revix7 on DOTS.DEVSTAGELIBRARY (LIBRARY_ID, DEV_STAGE_LIBRARY_ID) tablespace indx;
create index DOTS.DEVSTAGELIBRARY_revix8 on DOTS.DEVSTAGELIBRARY (DEVELOPMENTAL_STAGE_ID, DEV_STAGE_LIBRARY_ID) tablespace indx;
create index DOTS.GENE_revix9 on DOTS.GENE (SEQUENCE_ONTOLOGY_ID, GENE_ID) tablespace indx;
create index DOTS.MUTUALINFORMATIONSCORE_revix1 on DOTS.MUTUALINFORMATIONSCORE (SECONDARY_PROFILE_ID, MUTUAL_INFORMATION_SCORE_ID) tablespace indx;
create index DOTS.MUTUALINFORMATIONSCORE_revix2 on DOTS.MUTUALINFORMATIONSCORE (PRIMARY_PROFILE_ID, MUTUAL_INFORMATION_SCORE_ID) tablespace indx;
create index DOTS.NASEQUENCEIMP_revix0 on DOTS.NASEQUENCEIMP (SEQUENCE_ONTOLOGY_ID, NA_SEQUENCE_ID) tablespace indx;
create index DOTS.PHYLOGENETICPROFILEMEMB_revix6 on DOTS.PHYLOGENETICPROFILEMEMBER (TAXON_ID, PHYLOGENETIC_PROFILE_MEMBER_ID) tablespace indx;
create index DOTS.PHYLOGENETICPROFILESET_revix7 on DOTS.PHYLOGENETICPROFILESET (PRED_ALG_INVOCATION_ID, PHYLOGENETIC_PROFILE_SET_ID) tablespace indx;
create index DOTS.PHYLOGENETICPROFILE_revix4 on DOTS.PHYLOGENETICPROFILE (PHYLOGENETIC_PROFILE_SET_ID, PHYLOGENETIC_PROFILE_ID) tablespace indx;
create index DOTS.PHYLOGENETICPROFILE_revix5 on DOTS.PHYLOGENETICPROFILE (NA_FEATURE_ID, PHYLOGENETIC_PROFILE_ID) tablespace indx;
create index DOTS.PROTEIN_revix1 on DOTS.PROTEIN (SEQUENCE_ONTOLOGY_ID, PROTEIN_ID) tablespace indx;
create index DOTS.REJECTEDMOTIF_revix1 on DOTS.REJECTEDMOTIF (MOTIF_REJECTION_REASON_ID, REJECTED_MOTIF_ID) tablespace indx;
create index DOTS.REJECTEDMOTIF_revix2 on DOTS.REJECTEDMOTIF (EXTERNAL_DATABASE_RELEASE_ID, REJECTED_MOTIF_ID) tablespace indx;
create index DOTS.REJECTEDMOTIF_revix3 on DOTS.REJECTEDMOTIF (EXTERNAL_DATABASE_ID, REJECTED_MOTIF_ID) tablespace indx;
create index DOTS.RNA_revix4 on DOTS.RNA (SEQUENCE_ONTOLOGY_ID, RNA_ID) tablespace indx;
create index DOTS.SECONDARYSTRUCTURE_revix8 on DOTS.SECONDARYSTRUCTURE (PRED_ALG_INVOCATION_ID, SECONDARY_STRUCTURE_ID) tablespace indx;
create index DOTS.SECONDARYSTRUCTURE_revix9 on DOTS.SECONDARYSTRUCTURE (AA_SEQUENCE_ID, SECONDARY_STRUCTURE_ID) tablespace indx;
create index PROT.ACQUISITIONCHAIN_revix2 on PROT.ACQUISITIONCHAIN (CHILD_ACQUISITION_ID, ACQUISITION_CHAIN_ID) tablespace indx;
create index PROT.ACQUISITIONCHAIN_revix3 on PROT.ACQUISITIONCHAIN (PARENT_ACQUISITION_ID, ACQUISITION_CHAIN_ID) tablespace indx;
create index PROT.ACQUISITIONCHANNEL_revix4 on PROT.ACQUISITIONCHANNEL (ONTOLOGY_ENTRY_ID, ACQUISITION_CHANNEL_ID) tablespace indx;
create index PROT.ACQUISITIONCHANNEL_revix5 on PROT.ACQUISITIONCHANNEL (ACQUISITION_ID, ACQUISITION_CHANNEL_ID) tablespace indx;
create index PROT.ACQUISITIONIMP_revix6 on PROT.ACQUISITIONIMP (PROTOCOL_INSTANCE_ID, ACQUISITION_ID) tablespace indx;
create index PROT.ACQUISITIONIMP_revix7 on PROT.ACQUISITIONIMP (ASSAY_ID, ACQUISITION_ID) tablespace indx;
create index PROT.ACQUISITIONQUANTIFICATI_revix8 on PROT.ACQUISITIONQUANTIFICATION (QUANTIFICATION_ID, ACQUISITION_QUANTIFICATION_ID) tablespace indx;
create index PROT.ACQUISITIONQUANTIFICATI_revix9 on PROT.ACQUISITIONQUANTIFICATION (ACQUISITION_ID, ACQUISITION_QUANTIFICATION_ID) tablespace indx;
create index PROT.ASSAYCHAIN_revix0 on PROT.ASSAYCHAIN (TARGET_ASSAY_ID, ASSAY_CHAIN_ID) tablespace indx;
create index PROT.ASSAYCHAIN_revix1 on PROT.ASSAYCHAIN (SOURCE_ASSAY_ID, ASSAY_CHAIN_ID) tablespace indx;
create index PROT.ASSAYIMP_revix2 on PROT.ASSAYIMP (FEATURE_SET_ID, ASSAY_ID) tablespace indx;
create index PROT.ASSAYIMP_revix3 on PROT.ASSAYIMP (ASSAY_TYPE_ID, ASSAY_ID) tablespace indx;
create index PROT.ASSAYINPUT_revix4 on PROT.ASSAYINPUT (BIO_MATERIAL_MEASUREMENT_ID, ASSAY_INPUT_ID) tablespace indx;
create index PROT.ASSAYINPUT_revix5 on PROT.ASSAYINPUT (ASSAY_ID, ASSAY_INPUT_ID) tablespace indx;
create index PROT.ASSAYPARENTFILE_revix6 on PROT.ASSAYPARENTFILE (PARENT_FILE_ID, ASSAY_PARENT_FILE_ID) tablespace indx;
create index PROT.ASSAYPRODUCT_revix7 on PROT.ASSAYPRODUCT (FEATURE_ID, ASSAY_PRODUCT_ID) tablespace indx;
create index PROT.ASSAYPRODUCT_revix8 on PROT.ASSAYPRODUCT (ASSAY_ID, ASSAY_PRODUCT_ID) tablespace indx;
create index PROT.ASSAYPRODUCT_revix9 on PROT.ASSAYPRODUCT (BIO_MATERIAL_MEASUREMENT_ID, ASSAY_PRODUCT_ID) tablespace indx;
create index PROT.DATATRANSFORMATION_revix0 on PROT.DATATRANSFORMATION (INPUT_QUANTIFICATION_ID, DATA_TRANSFORMATION_IO_ID) tablespace indx;
create index PROT.DATATRANSFORMATION_revix1 on PROT.DATATRANSFORMATION (QUANTIFICATION_ID, DATA_TRANSFORMATION_IO_ID) tablespace indx;
create index PROT.ELEMENTRESULTIMP_revix2 on PROT.ELEMENTRESULTIMP (QUANTIFICATION_ID, ELEMENT_RESULT_ID) tablespace indx;
create index PROT.FEATUREIMP_revix3 on PROT.FEATUREIMP (FEATURE_SET_ID, FEATURE_ID) tablespace indx;
create index PROT.FEATUREINPUT_revix4 on PROT.FEATUREINPUT (FEATURE_ID, FEATURE_INPUT_ID) tablespace indx;
create index PROT.FEATUREINPUT_revix5 on PROT.FEATUREINPUT (ACQUISITION_ID, FEATURE_INPUT_ID) tablespace indx;
create index PROT.FEATURESETIMP_revix6 on PROT.FEATURESETIMP (PROTOCOL_INSTANCE_ID, FEATURE_SET_ID) tablespace indx;
create index PROT.FEATURESETIMP_revix7 on PROT.FEATURESETIMP (TECHNOLOGY_TYPE_ID, FEATURE_SET_ID) tablespace indx;
create index PROT.FEATURESETIMP_revix8 on PROT.FEATURESETIMP (SURFACE_TYPE_ID, FEATURE_SET_ID) tablespace indx;
create index PROT.FSGANNOTATION_revix6 on PROT.FSGANNOTATION (FEATURE_SET_ID, FSG_ANNOTATION_ID) tablespace indx;
create index PROT.PARAMETERINSTANCE_revix1 on PROT.PARAMETERINSTANCE (VALUE_ONTOLOGY_ENTRY_ID, PARAMETER_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERINSTANCE_revix2 on PROT.PARAMETERINSTANCE (PARAMETER_ID, PARAMETER_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERINSTANCE_revix3 on PROT.PARAMETERINSTANCE (PARAMETERIZABLE_INSTANCE_ID, PARAMETER_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERIZABLEIMP_revix4 on PROT.PARAMETERIZABLEIMP (CHILD_PRMZ_ID, PARAMETERIZABLE_ID) tablespace indx;
create index PROT.PARAMETERIZABLEINSTANCE_revix5 on PROT.PARAMETERIZABLEINSTANCEIMP (CHILD_PI_ID, PARAMETERIZABLE_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERIZABLEINSTANCE_revix6 on PROT.PARAMETERIZABLEINSTANCEIMP (PARENT_PI_ID, PARAMETERIZABLE_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERIZABLEINSTANCE_revix7 on PROT.PARAMETERIZABLEINSTANCEIMP (PARAMETERIZABLE_ID, PARAMETERIZABLE_INSTANCE_ID) tablespace indx;
create index PROT.PARAMETERIZABLELINKIMP_revix8 on PROT.PARAMETERIZABLELINKIMP (CHILD_PRMZ_ID, PARAMETERIZABLE_LINK_ID) tablespace indx;
create index PROT.PARAMETERIZABLELINKIMP_revix9 on PROT.PARAMETERIZABLELINKIMP (PARENT_PRMZ_ID, PARAMETERIZABLE_LINK_ID) tablespace indx;
create index PROT.PARAMETER_revix0 on PROT.PARAMETER (PARAMETERIZABLE_ID, PARAMETER_ID) tablespace indx;
create index PROT.PARAMETER_revix7 on PROT.PARAMETER (VALUE_CLASS_OE_ID, PARAMETER_ID) tablespace indx;
create index PROT.PARAMETER_revix8 on PROT.PARAMETER (UNIT_TYPE_ID, PARAMETER_ID) tablespace indx;
create index PROT.PARAMETER_revix9 on PROT.PARAMETER (DATA_TYPE_ID, PARAMETER_ID) tablespace indx;
create index PROT.PARENTFILE_revix5 on PROT.PARENTFILE (PARENT_FILE_TYPE_ID, PARENT_FILE_ID) tablespace indx;
create index PROT.QUANTIFICATIONIMP_revix6 on PROT.QUANTIFICATIONIMP (PROTOCOL_INSTANCE_ID, QUANTIFICATION_ID) tablespace indx;
create index PROT.STUDYFACTORVALUE_revix1 on PROT.STUDYFACTORVALUE (MEASUREMENT_UNIT_TYPE_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index PROT.STUDYFACTORVALUE_revix2 on PROT.STUDYFACTORVALUE (VALUE_ONTOLOGY_ENTRY_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index PROT.STUDYFACTORVALUE_revix3 on PROT.STUDYFACTORVALUE (ASSAY_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index PROT.STUDYFACTORVALUE_revix4 on PROT.STUDYFACTORVALUE (STUDY_FACTOR_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index RAD.ACQUISITIONPARAM_revix9 on RAD.ACQUISITIONPARAM (PROTOCOL_PARAM_ID, ACQUISITION_PARAM_ID) tablespace indx;
create index RAD.ANALYSISINPUT_revix4 on RAD.ANALYSISINPUT (ANALYSIS_ID, ANALYSIS_INPUT_ID) tablespace indx;
create index RAD.ANALYSISINPUT_revix5 on RAD.ANALYSISINPUT (LOGICAL_GROUP_ID, ANALYSIS_INPUT_ID) tablespace indx;
create index RAD.ANALYSISPARAM_revix6 on RAD.ANALYSISPARAM (PROTOCOL_PARAM_ID, ANALYSIS_PARAM_ID) tablespace indx;
create index RAD.ANALYSISPARAM_revix7 on RAD.ANALYSISPARAM (ANALYSIS_ID, ANALYSIS_PARAM_ID) tablespace indx;
create index RAD.ANALYSISQCPARAM_revix5 on RAD.ANALYSISQCPARAM (PROTOCOL_QC_PARAM_ID, ANALYSIS_QC_PARAM_ID) tablespace indx;
create index RAD.ANALYSISQCPARAM_revix6 on RAD.ANALYSISQCPARAM (ANALYSIS_ID, ANALYSIS_QC_PARAM_ID) tablespace indx;
create index RAD.ANALYSIS_revix0 on RAD.ANALYSIS (PROTOCOL_ID, ANALYSIS_ID) tablespace indx;
create index RAD.ANALYSIS_revix1 on RAD.ANALYSIS (OPERATOR_ID, ANALYSIS_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix0 on RAD.ARRAYDESIGN (SUBSTRATE_TYPE_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix1 on RAD.ARRAYDESIGN (TECHNOLOGY_TYPE_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix2 on RAD.ARRAYDESIGN (MANUFACTURER_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix7 on RAD.ARRAYDESIGN (SURFACE_TYPE_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix8 on RAD.ARRAYDESIGN (EXTERNAL_DATABASE_RELEASE_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ARRAYDESIGN_revix9 on RAD.ARRAYDESIGN (PROTOCOL_ID, ARRAY_DESIGN_ID) tablespace indx;
create index RAD.ASSAYANALYSIS_revix0 on RAD.ASSAYANALYSIS (ANALYSIS_ID, ASSAY_ANALYSIS_ID) tablespace indx;
create index RAD.ASSAYCONTROL_revix1 on RAD.ASSAYCONTROL (UNIT_TYPE_ID, ASSAY_CONTROL_ID) tablespace indx;
create index RAD.COMPOSITEELEMENTDBREF_revix6 on RAD.COMPOSITEELEMENTDBREF (DB_REF_ID, COMPOSITE_ELEMENT_DB_REF_ID) tablespace indx;
create index RAD.COMPOSITEELEMENTDBREF_revix7 on RAD.COMPOSITEELEMENTDBREF (COMPOSITE_ELEMENT_ID, COMPOSITE_ELEMENT_DB_REF_ID) tablespace indx;
create index RAD.COMPOSITEELEMENTNASEQUE_revix0 on RAD.COMPOSITEELEMENTNASEQUENCE (NA_SEQUENCE_ID, COMPOSITE_ELEMENT_NA_SEQ_ID) tablespace indx;
create index RAD.COMPOSITEELEMENTNASEQUE_revix1 on RAD.COMPOSITEELEMENTNASEQUENCE (COMPOSITE_ELEMENT_ID, COMPOSITE_ELEMENT_NA_SEQ_ID) tablespace indx;
create index RAD.CONTROL_revix2 on RAD.CONTROL (UNIT_TYPE_ID, CONTROL_ID) tablespace indx;
create index RAD.ELEMENTDBREF_revix3 on RAD.ELEMENTDBREF (DB_REF_ID, ELEMENT_DB_REF_ID) tablespace indx;
create index RAD.ELEMENTDBREF_revix4 on RAD.ELEMENTDBREF (ELEMENT_ID, ELEMENT_DB_REF_ID) tablespace indx;
create index RAD.ELEMENTIMP_revix3 on RAD.ELEMENTIMP (POLYMER_TYPE_ID, ELEMENT_ID) tablespace indx;
create index RAD.ELEMENTIMP_revix4 on RAD.ELEMENTIMP (PHYSICAL_BIOSEQUENCE_TYPE_ID, ELEMENT_ID) tablespace indx;
create index RAD.ELEMENTNASEQUENCE_revix5 on RAD.ELEMENTNASEQUENCE (ELEMENT_ID, ELEMENT_NA_SEQUENCE_ID) tablespace indx;
create index RAD.LOGICALGROUPLINK_revix6 on RAD.LOGICALGROUPLINK (TABLE_ID, LOGICAL_GROUP_LINK_ID) tablespace indx;
create index RAD.LOGICALGROUPLINK_revix7 on RAD.LOGICALGROUPLINK (LOGICAL_GROUP_ID, LOGICAL_GROUP_LINK_ID) tablespace indx;
create index RAD.PROTOCOLQCPARAM_revix2 on RAD.PROTOCOLQCPARAM (UNIT_TYPE_ID, PROTOCOL_QC_PARAM_ID) tablespace indx;
create index RAD.PROTOCOLQCPARAM_revix3 on RAD.PROTOCOLQCPARAM (DATA_TYPE_ID, PROTOCOL_QC_PARAM_ID) tablespace indx;
create index RAD.PROTOCOLQCPARAM_revix4 on RAD.PROTOCOLQCPARAM (PROTOCOL_ID, PROTOCOL_QC_PARAM_ID) tablespace indx;
create index RAD.PROTOCOLSTEP_revix5 on RAD.PROTOCOLSTEP (CHILD_PROTOCOL_ID, PROTOCOL_STEP_ID) tablespace indx;
create index RAD.PROTOCOL_revix8 on RAD.PROTOCOL (EXTERNAL_DATABASE_RELEASE_ID, PROTOCOL_ID) tablespace indx;
create index RAD.PROTOCOL_revix9 on RAD.PROTOCOL (BIBLIOGRAPHIC_REFERENCE_ID, PROTOCOL_ID) tablespace indx;
create index RAD.QUANTIFICATIONPARAM_revix6 on RAD.QUANTIFICATIONPARAM (PROTOCOL_PARAM_ID, QUANTIFICATION_PARAM_ID) tablespace indx;
create index RAD.STUDYFACTORVALUE_revix0 on RAD.STUDYFACTORVALUE (CHANNEL_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index RAD.STUDYFACTORVALUE_revix1 on RAD.STUDYFACTORVALUE (MEASUREMENT_UNIT_OE_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index RAD.STUDYFACTORVALUE_revix2 on RAD.STUDYFACTORVALUE (VALUE_ONTOLOGY_ENTRY_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index RAD.STUDYFACTORVALUE_revix3 on RAD.STUDYFACTORVALUE (ASSAY_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index RAD.STUDYFACTORVALUE_revix4 on RAD.STUDYFACTORVALUE (STUDY_FACTOR_ID, STUDY_FACTOR_VALUE_ID) tablespace indx;
create index SRES.ANATOMYSAEL_revix7 on SRES.ANATOMYSAEL (SAEL_ID, ANATOMY_SAEL_ID) tablespace indx;
create index SRES.ANATOMYSAEL_revix8 on SRES.ANATOMYSAEL (ANATOMY_ID, ANATOMY_SAEL_ID) tablespace indx;
create index SRES.BIBLIOGRAPHICREFERENCE_revix9 on SRES.BIBLIOGRAPHICREFERENCE (EXTERNAL_DATABASE_RELEASE_ID, BIBLIOGRAPHIC_REFERENCE_ID) tablespace indx;
create index SRES.SAEL_revix8 on SRES.SAEL (EXTERNAL_DATABASE_RELEASE_ID, SAEL_ID) tablespace indx;
create index STUDY.BMCRELATIONSHIP_revix5 on STUDY.BMCRELATIONSHIP (OBJECT_BMC_ID, BMC_RELATIONSHIP_ID) tablespace indx;
create index STUDY.BMCRELATIONSHIP_revix6 on STUDY.BMCRELATIONSHIP (PREDICATE_BMC_ID, BMC_RELATIONSHIP_ID) tablespace indx;
create index STUDY.BMCRELATIONSHIP_revix7 on STUDY.BMCRELATIONSHIP (SUBJECT_BMC_ID, BMC_RELATIONSHIP_ID) tablespace indx;
create index TESS.ARCHIPELAGOOFINTEREST_revix8 on TESS.ARCHIPELAGOOFINTEREST (EXTERNAL_DATABASE_RELEASE_ID, ARCHIPELAGO_OF_INTEREST_ID) tablespace indx;
create index TESS.ISLANDOFINTEREST_revix2 on TESS.ISLANDOFINTEREST (ARCHIPELAGO_OF_INTEREST_ID, ISLAND_OF_INTEREST_ID) tablespace indx;
create index TESS.MARKOVCHAINOBS_revix3 on TESS.MARKOVCHAINOBS (MULTINOMIAL_OBSERVATION_SET_ID, MARKOV_CHAIN_OBS_ID) tablespace indx;
create index TESS.MARKOVCHAINOBS_revix4 on TESS.MARKOVCHAINOBS (MODEL_ID, MARKOV_CHAIN_OBS_ID) tablespace indx;
create index TESS.MULTINOMIALOBSERVATIONS_revix9 on TESS.MULTINOMIALOBSERVATIONSET (MULTINOMIAL_LABEL_SET_ID, MULTINOMIAL_OBS_SET_ID) tablespace indx;
create index TESS.MULTINOMIALOBSERVATION_revix8 on TESS.MULTINOMIALOBSERVATION (MULTINOMIAL_OBS_SET_ID, MULTINOMIAL_OBS_ID) tablespace indx;
create index TESS.REGIONOFINTEREST_revix8 on TESS.REGIONOFINTEREST (NA_FEATURE_ID, REGION_OF_INTEREST_ID) tablespace indx;
create index TESS.REGIONOFINTEREST_revix9 on TESS.REGIONOFINTEREST (ISLAND_OF_INTEREST_ID, REGION_OF_INTEREST_ID) tablespace indx;
create index TESS.SBCGRECOGMULTIOBS_revix0 on TESS.SBCGRECOGMULTIOBS (SBCG_RECOGNITION_ID, SBCG_RECOG_MULTI_OBS_ID) tablespace indx;

exit
