--
-- patch script for unwanted exons and proteins on pseudogenes
--
-- creates tables listing na_feature_ids (of transcripts), aa_feature_ids, and
-- aa_sequence_ids to remove, and copies affected records of each table X to a
-- new table "PGP_X" (for "pseudogenes patch")
--

-- organism-scoped gene na_feature_ids
create table apidb.pgp_pseudoGeneId as
select gf.na_feature_id
from dots.GeneFeature gf
  join dots.NaSequence ns on gf.na_sequence_id = ns.na_sequence_id
  join apidb.Organism o on ns.taxon_id = o.taxon_id
where o.public_abbrev = ':ORG_ABBREV';

-- set IS_PSEUDO for genes named "pseudogene", and their transcripts, where it isn't already
update dots.Transcript
set is_pseudo = 1
where is_pseudo = 0
  and na_feature_id in (
    select t.na_feature_id
    from dots.Transcript t
      join dots.GeneFeature gf on t.parent_id = gf.na_feature_id
      join apidb.pgp_pseudoGeneId pg on gf.na_feature_id = pg.na_feature_id
    where gf.name = 'pseudogene'
  );

update dots.GeneFeature
set is_pseudo = 1
where is_pseudo = 0
  and name = 'pseudogene'
  and na_feature_id in (select na_feature_id from apidb.pgp_pseudoGeneId);

-- create lists of IDs of affected NaFeature / AaFeature / AaSequence records
create table apidb.new_pseudoNaFeatureId as
select t.na_feature_id
from dots.Transcript t
  join apidb.pgp_pseudoGeneId pg on t.parent_id = pg.na_feature_id
where t.is_pseudo = 1;

create table apidb.new_pseudoAaFeatureId as
select taf.aa_feature_id
from dots.TranslatedAaFeature taf
  join apidb.new_pseudoNaFeatureId pnf on taf.na_feature_id = pnf.na_feature_id;

create table apidb.new_pseudoAaSequenceId as
select taf.aa_sequence_id
from dots.TranslatedAaFeature taf
  join apidb.new_pseudoNaFeatureId pnf on taf.na_feature_id = pnf.na_feature_id;

--------------------------------------------------------------------------------
-- set coding start/end NULL

create table apidb.pgp2_RnaFeatureExon as
select *
from dots.RnaFeatureExon
where (coding_start is not null or coding_end is not null)
  and rna_feature_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);

update dots.RnaFeatureExon
set coding_start = null,
    coding_end = null
where (coding_start is not null or coding_end is not null)
  and rna_feature_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);

--------------------------------------------------------------------------------

create table apidb.pgp2_SecondaryStructureCall as
select *
from dots.SecondaryStructureCall
where secondary_structure_id in (
  select ss.secondary_structure_id
  from dots.SecondaryStructure ss
    join apidb.new_pseudoAaSequenceId pasi on ss.aa_sequence_id = pasi.aa_sequence_id
);

delete from dots.SecondaryStructureCall
where secondary_structure_id in (
  select ss.secondary_structure_id
  from dots.SecondaryStructure ss
    join apidb.new_pseudoAaSequenceId pasi on ss.aa_sequence_id = pasi.aa_sequence_id
);


create table apidb.pgp2_SecondaryStructure as
select *
from dots.SecondaryStructure
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from dots.SecondaryStructure
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);


create table apidb.pgp2_DbRefAaFeature as
select *
from dots.DbRefAaFeature
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);

delete from dots.DbRefAaFeature
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);


create table apidb.pgp2_AaFeatureExon as
select *
from dots.AaFeatureExon
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);

delete from dots.AaFeatureExon
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);


create table apidb.pgp2_AaLocation as
select *
from dots.AaLocation
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);

delete from dots.AaLocation
where aa_feature_id in (
  select aaf.aa_feature_id
  from dots.AaFeature aaf
    join apidb.new_pseudoAaSequenceId pasi on aaf.aa_sequence_id = pasi.aa_sequence_id
);


create table apidb.pgp2_AaFeature as
select *
from dots.AaFeature
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from dots.AaFeature
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);


create table apidb.pgp2_AaSequenceAttribute as
select *
from apidb.AaSequenceAttribute
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from apidb.AaSequenceAttribute
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);


create table apidb.pgp2_MassSpecSummary as
select *
from apidb.MassSpecSummary
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from apidb.MassSpecSummary
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);


create table apidb.pgp2_AaSequenceEnzymeClass as
select *
from dots.AaSequenceEnzymeClass
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from dots.AaSequenceEnzymeClass
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);


create table apidb.pgp2_TranslatedAASequence as
select *
from dots.TranslatedAASequence
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

delete from dots.TranslatedAASequence
where aa_sequence_id in (select aa_sequence_id from apidb.new_pseudoAaSequenceId);

--------------------------------------------------------------------------------

create table apidb.pgp2_TranslatedAaFeature as
select *
from dots.TranslatedAaFeature
where na_feature_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);

delete from dots.TranslatedAaFeature
where na_feature_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);


create table apidb.pgp2_FeatureLocation as
select *
from apidb.FeatureLocation
where feature_type in ('UTR', 'CDS')
  and parent_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);

delete from apidb.FeatureLocation
where feature_type in ('UTR', 'CDS')
  and parent_id in (select na_feature_id from apidb.new_pseudoNaFeatureId);

--------------------------------------------------------------------------------
-- cleanup

drop table apidb.pgp_pseudoGeneId;
drop table apidb.new_pseudoNaFeatureId;
drop table apidb.new_pseudoAaFeatureId;
drop table apidb.new_pseudoAaSequenceId;
drop table apidb.pgp2_RnaFeatureExon;
drop table apidb.pgp2_SecondaryStructureCall;
drop table apidb.pgp2_SecondaryStructure;
drop table apidb.pgp2_DbRefAaFeature;
drop table apidb.pgp2_AaFeatureExon;
drop table apidb.pgp2_AaLocation;
drop table apidb.pgp2_AaFeature;
drop table apidb.pgp2_AaSequenceAttribute;
drop table apidb.pgp2_MassSpecSummary;
drop table apidb.pgp2_AaSequenceEnzymeClass;
drop table apidb.pgp2_TranslatedAASequence;
drop table apidb.pgp2_TranslatedAaFeature;
drop table apidb.pgp2_FeatureLocation;
