# Count variable number under "Sample" category

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT (COUNT(DISTINCT ?variable) AS ?variable_num)
WHERE { 
	?entity rdfs:subClassOf* obo:EUPATH_0000609 . #Sample
	?entity obo:EUPATH_0000755 ?variable .
}