# Get total number of distinct ontology classes(terms) in the OWL file

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(DISTINCT ?term) AS ?terms_num)
WHERE { 
	?term a owl:Class .
}
