PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?IRI ?presence_label ?parent
WHERE {
  ?IRI rdfs:label ?presence_label .
  ?IRI rdfs:subClassOf ?parentIRI .
  ?parentIRI rdfs:label ?parent .
  FILTER regex(str(?presence_label), ", by") .
}