# Number of datasets the ontology classes(terms) were used and indicate whether they have same labels among multiple datasets
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT distinct ?IRI 
  (GROUP_CONCAT(DISTINCT ?slabel;separator=" | ") AS ?label)
  (GROUP_CONCAT(DISTINCT ?dOrder;separator=" | ") AS ?displayOrder)
  (GROUP_CONCAT(DISTINCT ?var;separator=" | ") AS ?variable)
  (GROUP_CONCAT(DISTINCT ?dFile;separator=" | ") AS ?dataFile)
  (GROUP_CONCAT(DISTINCT ?def;separator=" | ") AS ?definition)
  (GROUP_CONCAT(DISTINCT ?cate;separator=" | ") AS ?category)
  (GROUP_CONCAT(DISTINCT ?pLabel;separator=" | ") AS ?parentLabel)
  (GROUP_CONCAT(DISTINCT ?pIRI;separator=" | ") AS ?parentIRI)
  (GROUP_CONCAT(DISTINCT ?cDescription;separator=" | ") AS ?codebookDescription)
  (GROUP_CONCAT(DISTINCT ?cValues;separator=" | ") AS ?codebookValues)
  (GROUP_CONCAT(DISTINCT ?tType;separator=" | ") AS ?termType)
  (GROUP_CONCAT(DISTINCT ?rep;separator=" | ") AS ?replaces)
  (GROUP_CONCAT(DISTINCT ?unitL;separator=" | ") AS ?unitLabel)
  (GROUP_CONCAT(DISTINCT ?unitI;separator=" | ") AS ?unitIRI)
  (GROUP_CONCAT(DISTINCT ?dataS;separator=" | ") AS ?dataSet)
  (GROUP_CONCAT(DISTINCT ?timeV;separator=" | ") AS ?timeVarying)
  (GROUP_CONCAT(DISTINCT ?keyV;separator=" | ") AS ?keyVar)
  (GROUP_CONCAT(DISTINCT ?hid;separator=" | ") AS ?hidden)
  (GROUP_CONCAT(DISTINCT ?scal;separator=" | ") AS ?scale)
WHERE {
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:PCO_0000024 .
	BIND ("Household" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0000327 .
	BIND ("Entomology" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0025169 .
	BIND ("Insect sample" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0000096 .
	BIND ("Participant" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0000609 .
	BIND ("Sample" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0035127 .
	BIND ("Community" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
	UNION
	{?IRI rdfs:label ?tlabel .
	?IRI rdfs:subClassOf* obo:EUPATH_0000738 .
	BIND ("Observation" AS ?cate) .
    	FILTER not exists { 
      		?IRI owl:deprecated ?dep .
    	}
	BIND (str(?tlabel) AS ?slabel) .
	OPTIONAL {
		?IRI obo:EUPATH_0000274 ?dOrder .
    	}
     	OPTIONAL {
        	?IRI obo:EUPATH_0000755 ?var .
    	} 
    	OPTIONAL {
        	?IRI obo:EUPATH_0001001 ?dFile .
    	}
    	OPTIONAL {
        	?IRI obo:IAO_0000115 ?def .
    	}
	OPTIONAL {
		?IRI rdfs:subClassOf ?pIRI .
	}
	OPTIONAL {
		?pIRI rdfs:label ?palabel . 
		BIND (str(?palabel) AS ?pLabel) .
	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001003 ?cDescription .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001004 ?cValues .
    	}
    	OPTIONAL {
        	?IRI obo:EUPATH_0001005 ?tType .
    	}
        OPTIONAL {
            ?IRI obo:EUPATH_0001006 ?rep .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001008 ?unitL .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001009 ?unitI .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001010 ?dataS .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001011 ?timeV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001012 ?keyV .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001013 ?hid .
        }
        OPTIONAL {
            ?IRI obo:EUPATH_0001014 ?scal .
        }
	}
}
GROUP BY ?IRI
ORDER BY ASC(?category) ASC(?parentLabel) ASC(?label)