# Find terms with more than one parent

PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


SELECT ?sid
  (COUNT(DISTINCT ?label) AS ?label_count)
  (GROUP_CONCAT(DISTINCT ?label;separator="|") AS ?labels)
WHERE {
  ?entity a owl:Class .
  ?entity rdfs:label ?org_label .
  BIND (str(?org_label) AS ?label) .
  BIND(COALESCE(
	IF(CONTAINS(STR(?entity), "/obo/"), STRAFTER(STR(?entity), "/obo/"), ?c), 
	IF(CONTAINS(STR(?entity), "/efo/"), STRAFTER(STR(?entity), "/efo/"), ?c),
	IF(CONTAINS(STR(?entity), "#"), STRAFTER(STR(?entity), "#"), ?c),
 	REPLACE(STRAFTER(STR(?entity), "/ontology/"), "/", "_")) AS ?sid)
}
GROUP BY ?sid
HAVING (?label_count > 1)
ORDER BY DESC(?label_count)
