# List unit label and IRI group by unit label

PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?unitLabel
  (COUNT(DISTINCT ?unitIRI_str) AS ?unit_count)
  (GROUP_CONCAT(DISTINCT ?unitIRI_str;separator="|") AS ?unitIRI)
WHERE {
  ?entity obo:EUPATH_0001008 ?unitLabel .
  OPTIONAL {
	?entity obo:EUPATH_0001009 ?uIRI . 
  }
  BIND(IF(bound(?uIRI), ?uIRI, "NO_IRI") AS ?unitIRI_str)
}
GROUP BY ?unitLabel
ORDER BY ASC(?unit_count) ASC(?unitLabel)
