# Update category annotation values

PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

INSERT { ?s obo:EUPATH_0001002 'Observation' }
WHERE  { ?s rdfs:subClassOf* obo:EUPATH_0000738 }
