CREATE USER chebi
IDENTIFIED BY VALUES '36811EDD93CB4A00'  -- encoding of standard password
QUOTA UNLIMITED ON users 
QUOTA UNLIMITED ON gus
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT GUS_R TO chebi;
GRANT GUS_W TO chebi;
GRANT CREATE VIEW TO chebi;
GRANT CREATE MATERIALIZED VIEW TO chebi;
GRANT CREATE TABLE TO chebi;
GRANT CREATE SYNONYM TO chebi;
GRANT CREATE SESSION TO chebi;
GRANT CREATE ANY INDEX TO chebi;
GRANT CREATE TRIGGER TO chebi;
GRANT CREATE ANY TRIGGER TO chebi;

-- GRANTs required for CTXSYS
GRANT CONNECT, RESOURCE, CTXAPP, GUS_W to chebi;

exit
