DROP VIEW dots.TranslatedAaFeature;

CREATE VIEW dots.TranslatedAaFeature AS
SELECT AA_FEATURE_ID, AA_SEQUENCE_ID, FEATURE_NAME_ID, PARENT_ID,
       NA_FEATURE_ID, SUBCLASS_VIEW, SEQUENCE_ONTOLOGY_ID, DESCRIPTION,
       EXTERNAL_DATABASE_RELEASE_ID, SOURCE_ID,
       PREDICTION_ALGORITHM_ID, IS_PREDICTED, REVIEW_STATUS_ID,
       NUMBER1 AS TRANSLATION_START, NUMBER2 AS TRANSLATION_STOP,
       NUMBER3 AS IS_SIMPLE, STRING1 AS CODON_TABLE,
       FLOAT1 AS TRANSLATION_SCORE, STRING2 AS TRANSLATION_MODEL,
       NUMBER4 AS NUMBER_OF_SEGMENTS, FLOAT2 AS DIANA_ATG_SCORE,
       NUMBER5 AS DIANA_ATG_POSITION, FLOAT3 AS P_VALUE,
       STRING3 AS PARAMETER_VALUES, NUMBER6 AS IS_REVERSED, MODIFICATION_DATE,
       USER_READ, USER_WRITE, GROUP_READ, GROUP_WRITE, OTHER_READ, OTHER_WRITE,
       ROW_USER_ID, ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
FROM dots.AaFeatureImp
WHERE subclass_view='TranslatedAAFeature';

GRANT SELECT ON dots.TranslatedAaFeature TO gus_r;

GRANT INSERT, UPDATE, DELETE ON dots.TranslatedAaFeature TO gus_w;

exit
