-- BYTEA is not supported in GUS
-- This table set seems to only be used for OrthoMCL.
-- Disable for now.

-- ora-only --CREATE TABLE apidb.OrthologGroup (
-- ora-only -- ortholog_group_id            NUMERIC(12) NOT NULL,
-- ora-only -- subclass_view                character varying(30) NOT NULL,
-- ora-only -- name                         character varying(500),
-- ora-only -- description                  character varying(2000),
-- ora-only -- NUMERIC_of_members            NUMERIC(12) NOT NULL,
-- ora-only -- avg_percent_identity         FLOAT,
-- ora-only -- avg_percent_match            FLOAT,
-- ora-only -- avg_evalue_mant              FLOAT,
-- ora-only -- avg_evalue_exp               NUMERIC,
-- ora-only -- avg_connectivity             FLOAT(40),
-- ora-only -- NUMERIC_of_match_pairs        NUMERIC,
-- ora-only -- aa_seq_group_experiment_id   NUMERIC(12),
-- ora-only -- external_database_release_id NUMERIC(10) NOT NULL,
-- ora-only -- multiple_sequence_alignment  TEXT,
-- ora-only -- biolayout_image              BYTEA,
-- ora-only -- svg_content                  TEXT,
-- ora-only -- modification_date            timestamp NOT NULL,
-- ora-only -- user_read                    NUMERIC(1) NOT NULL,
-- ora-only -- user_write                   NUMERIC(1) NOT NULL,
-- ora-only -- group_read                   NUMERIC(1) NOT NULL,
-- ora-only -- group_write                  NUMERIC(1) NOT NULL,
-- ora-only -- other_read                   NUMERIC(1) NOT NULL,
-- ora-only -- other_write                  NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                  NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                 NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id               NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id        NUMERIC(12) NOT NULL
-- ora-only --);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthologGroup
-- ora-only --ADD CONSTRAINT og_pk PRIMARY KEY (ortholog_group_id);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthologGroup
-- ora-only --ADD CONSTRAINT og_fk1 FOREIGN KEY (external_database_release_id)
-- ora-only --REFERENCES sres.ExternalDatabaseRelease;
-- ora-only --
-- ora-only --CREATE INDEX OrthologGroup_revix
-- ora-only --ON apidb.OrthologGroup (external_database_release_id, ortholog_group_id);
-- ora-only --
-- ora-only --CREATE INDEX og_name_ix ON apidb.OrthologGroup (name, ortholog_group_id);
-- ora-only --CREATE INDEX og_mem_ix ON apidb.OrthologGroup (NUMERIC_of_members, ortholog_group_id);
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE apidb.OrthologGroup_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthologGroup',
-- ora-only --       'Standard', 'ORTHOLOG_GROUP_ID',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthologGroup') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --------------------------------------------------------------------------------
-- ora-only --CREATE TABLE apidb.OrthomclTaxon (
-- ora-only -- orthomcl_taxon_id             NUMERIC(12) NOT NULL,
-- ora-only -- parent_id                     NUMERIC(12),
-- ora-only -- taxon_id                      NUMERIC(12),
-- ora-only -- name                          VARCHAR(255),
-- ora-only -- three_letter_abbrev           VARCHAR(6) NOT NULL,
-- ora-only -- is_species                    NUMERIC(1) NOT NULL,
-- ora-only -- species_order                 NUMERIC(4),
-- ora-only -- depth_first_index             NUMERIC(10) NOT NULL,
-- ora-only -- sibling_depth_first_index     NUMERIC(10),
-- ora-only -- common_name                   VARCHAR(255),
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL
-- ora-only --);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthomclTaxon
-- ora-only --ADD CONSTRAINT ot_pk UNIQUE (orthomcl_taxon_id);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthomclTaxon
-- ora-only --ADD CONSTRAINT ot_fk1 FOREIGN KEY (parent_id)
-- ora-only --REFERENCES apidb.OrthomclTaxon (orthomcl_taxon_id);
-- ora-only --
-- ora-only --CREATE INDEX OrthomclTaxon_revix
-- ora-only --ON apidb.OrthomclTaxon (parent_id, orthomcl_taxon_id);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthomclTaxon
-- ora-only --ADD CONSTRAINT ot_fk2 FOREIGN KEY (taxon_id)
-- ora-only --REFERENCES sres.Taxon (taxon_id);
-- ora-only --
-- ora-only --CREATE INDEX OrthomclTaxon_revix
-- ora-only --ON apidb.OrthomclTaxon (taxon_id, orthomcl_taxon_id);
-- ora-only --
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE apidb.OrthomclTaxon_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthomclTaxon',
-- ora-only --       'Standard', 'ORTHOMCL_TAXON_ID',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthomclTaxon') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --------------------------------------------------------------------------------
-- ora-only --CREATE TABLE apidb.GroupTaxonMatrix (
-- ora-only -- group_taxon_matrix_id       NUMERIC(12) NOT NULL,
-- ora-only -- ortholog_group_id       NUMERIC(12) NOT NULL,
-- ora-only -- column1                     NUMERIC(8),
-- ora-only -- column2                     NUMERIC(8),
-- ora-only -- column3                     NUMERIC(8),
-- ora-only -- column4                     NUMERIC(8),
-- ora-only -- column5                     NUMERIC(8),
-- ora-only -- column6                     NUMERIC(8),
-- ora-only -- column7                     NUMERIC(8),
-- ora-only -- column8                     NUMERIC(8),
-- ora-only -- column9                     NUMERIC(8),
-- ora-only -- column10                     NUMERIC(8),
-- ora-only -- column11                     NUMERIC(8),
-- ora-only -- column12                     NUMERIC(8),
-- ora-only -- column13                     NUMERIC(8),
-- ora-only -- column14                     NUMERIC(8),
-- ora-only -- column15                     NUMERIC(8),
-- ora-only -- column16                     NUMERIC(8),
-- ora-only -- column17                     NUMERIC(8),
-- ora-only -- column18                     NUMERIC(8),
-- ora-only -- column19                     NUMERIC(8),
-- ora-only -- column20                     NUMERIC(8),
-- ora-only -- column21                     NUMERIC(8),
-- ora-only -- column22                     NUMERIC(8),
-- ora-only -- column23                     NUMERIC(8),
-- ora-only -- column24                     NUMERIC(8),
-- ora-only -- column25                     NUMERIC(8),
-- ora-only -- column26                     NUMERIC(8),
-- ora-only -- column27                     NUMERIC(8),
-- ora-only -- column28                     NUMERIC(8),
-- ora-only -- column29                     NUMERIC(8),
-- ora-only -- column30                     NUMERIC(8),
-- ora-only -- column31                     NUMERIC(8),
-- ora-only -- column32                     NUMERIC(8),
-- ora-only -- column33                     NUMERIC(8),
-- ora-only -- column34                     NUMERIC(8),
-- ora-only -- column35                     NUMERIC(8),
-- ora-only -- column36                     NUMERIC(8),
-- ora-only -- column37                     NUMERIC(8),
-- ora-only -- column38                     NUMERIC(8),
-- ora-only -- column39                     NUMERIC(8),
-- ora-only -- column40                     NUMERIC(8),
-- ora-only -- column41                     NUMERIC(8),
-- ora-only -- column42                     NUMERIC(8),
-- ora-only -- column43                     NUMERIC(8),
-- ora-only -- column44                     NUMERIC(8),
-- ora-only -- column45                     NUMERIC(8),
-- ora-only -- column46                     NUMERIC(8),
-- ora-only -- column47                     NUMERIC(8),
-- ora-only -- column48                     NUMERIC(8),
-- ora-only -- column49                     NUMERIC(8),
-- ora-only -- column50                     NUMERIC(8),
-- ora-only -- column51                     NUMERIC(8),
-- ora-only -- column52                     NUMERIC(8),
-- ora-only -- column53                     NUMERIC(8),
-- ora-only -- column54                     NUMERIC(8),
-- ora-only -- column55                     NUMERIC(8),
-- ora-only -- column56                     NUMERIC(8),
-- ora-only -- column57                     NUMERIC(8),
-- ora-only -- column58                     NUMERIC(8),
-- ora-only -- column59                     NUMERIC(8),
-- ora-only -- column60                     NUMERIC(8),
-- ora-only -- column61                     NUMERIC(8),
-- ora-only -- column62                     NUMERIC(8),
-- ora-only -- column63                     NUMERIC(8),
-- ora-only -- column64                     NUMERIC(8),
-- ora-only -- column65                     NUMERIC(8),
-- ora-only -- column66                     NUMERIC(8),
-- ora-only -- column67                     NUMERIC(8),
-- ora-only -- column68                     NUMERIC(8),
-- ora-only -- column69                     NUMERIC(8),
-- ora-only -- column70                     NUMERIC(8),
-- ora-only -- column71                     NUMERIC(8),
-- ora-only -- column72                     NUMERIC(8),
-- ora-only -- column73                     NUMERIC(8),
-- ora-only -- column74                     NUMERIC(8),
-- ora-only -- column75                     NUMERIC(8),
-- ora-only -- column76                     NUMERIC(8),
-- ora-only -- column77                     NUMERIC(8),
-- ora-only -- column78                     NUMERIC(8),
-- ora-only -- column79                     NUMERIC(8),
-- ora-only -- column80                     NUMERIC(8),
-- ora-only -- column81                     NUMERIC(8),
-- ora-only -- column82                     NUMERIC(8),
-- ora-only -- column83                     NUMERIC(8),
-- ora-only -- column84                     NUMERIC(8),
-- ora-only -- column85                     NUMERIC(8),
-- ora-only -- column86                     NUMERIC(8),
-- ora-only -- column87                     NUMERIC(8),
-- ora-only -- column88                     NUMERIC(8),
-- ora-only -- column89                     NUMERIC(8),
-- ora-only -- column90                     NUMERIC(8),
-- ora-only -- column91                     NUMERIC(8),
-- ora-only -- column92                     NUMERIC(8),
-- ora-only -- column93                     NUMERIC(8),
-- ora-only -- column94                     NUMERIC(8),
-- ora-only -- column95                     NUMERIC(8),
-- ora-only -- column96                     NUMERIC(8),
-- ora-only -- column97                     NUMERIC(8),
-- ora-only -- column98                     NUMERIC(8),
-- ora-only -- column99                     NUMERIC(8),
-- ora-only -- column100                     NUMERIC(8),
-- ora-only -- column101                     NUMERIC(8),
-- ora-only -- column102                     NUMERIC(8),
-- ora-only -- column103                     NUMERIC(8),
-- ora-only -- column104                     NUMERIC(8),
-- ora-only -- column105                     NUMERIC(8),
-- ora-only -- column106                     NUMERIC(8),
-- ora-only -- column107                     NUMERIC(8),
-- ora-only -- column108                     NUMERIC(8),
-- ora-only -- column109                     NUMERIC(8),
-- ora-only -- column110                     NUMERIC(8),
-- ora-only -- column111                     NUMERIC(8),
-- ora-only -- column112                     NUMERIC(8),
-- ora-only -- column113                     NUMERIC(8),
-- ora-only -- column114                     NUMERIC(8),
-- ora-only -- column115                     NUMERIC(8),
-- ora-only -- column116                     NUMERIC(8),
-- ora-only -- column117                     NUMERIC(8),
-- ora-only -- column118                     NUMERIC(8),
-- ora-only -- column119                     NUMERIC(8),
-- ora-only -- column120                     NUMERIC(8),
-- ora-only -- column121                     NUMERIC(8),
-- ora-only -- column122                     NUMERIC(8),
-- ora-only -- column123                     NUMERIC(8),
-- ora-only -- column124                     NUMERIC(8),
-- ora-only -- column125                     NUMERIC(8),
-- ora-only -- column126                     NUMERIC(8),
-- ora-only -- column127                     NUMERIC(8),
-- ora-only -- column128                     NUMERIC(8),
-- ora-only -- column129                     NUMERIC(8),
-- ora-only -- column130                     NUMERIC(8),
-- ora-only -- column131                     NUMERIC(8),
-- ora-only -- column132                     NUMERIC(8),
-- ora-only -- column133                     NUMERIC(8),
-- ora-only -- column134                     NUMERIC(8),
-- ora-only -- column135                     NUMERIC(8),
-- ora-only -- column136                     NUMERIC(8),
-- ora-only -- column137                     NUMERIC(8),
-- ora-only -- column138                     NUMERIC(8),
-- ora-only -- column139                     NUMERIC(8),
-- ora-only -- column140                     NUMERIC(8),
-- ora-only -- column141                     NUMERIC(8),
-- ora-only -- column142                     NUMERIC(8),
-- ora-only -- column143                     NUMERIC(8),
-- ora-only -- column144                     NUMERIC(8),
-- ora-only -- column145                     NUMERIC(8),
-- ora-only -- column146                     NUMERIC(8),
-- ora-only -- column147                     NUMERIC(8),
-- ora-only -- column148                     NUMERIC(8),
-- ora-only -- column149                     NUMERIC(8),
-- ora-only -- column150                     NUMERIC(8),
-- ora-only -- column151                     NUMERIC(8),
-- ora-only -- column152                     NUMERIC(8),
-- ora-only -- column153                     NUMERIC(8),
-- ora-only -- column154                     NUMERIC(8),
-- ora-only -- column155                     NUMERIC(8),
-- ora-only -- column156                     NUMERIC(8),
-- ora-only -- column157                     NUMERIC(8),
-- ora-only -- column158                     NUMERIC(8),
-- ora-only -- column159                     NUMERIC(8),
-- ora-only -- column160                     NUMERIC(8),
-- ora-only -- column161                     NUMERIC(8),
-- ora-only -- column162                     NUMERIC(8),
-- ora-only -- column163                     NUMERIC(8),
-- ora-only -- column164                     NUMERIC(8),
-- ora-only -- column165                     NUMERIC(8),
-- ora-only -- column166                     NUMERIC(8),
-- ora-only -- column167                     NUMERIC(8),
-- ora-only -- column168                     NUMERIC(8),
-- ora-only -- column169                     NUMERIC(8),
-- ora-only -- column170                     NUMERIC(8),
-- ora-only -- column171                     NUMERIC(8),
-- ora-only -- column172                     NUMERIC(8),
-- ora-only -- column173                     NUMERIC(8),
-- ora-only -- column174                     NUMERIC(8),
-- ora-only -- column175                     NUMERIC(8),
-- ora-only -- column176                     NUMERIC(8),
-- ora-only -- column177                     NUMERIC(8),
-- ora-only -- column178                     NUMERIC(8),
-- ora-only -- column179                     NUMERIC(8),
-- ora-only -- column180                     NUMERIC(8),
-- ora-only -- column181                     NUMERIC(8),
-- ora-only -- column182                     NUMERIC(8),
-- ora-only -- column183                     NUMERIC(8),
-- ora-only -- column184                     NUMERIC(8),
-- ora-only -- column185                     NUMERIC(8),
-- ora-only -- column186                     NUMERIC(8),
-- ora-only -- column187                     NUMERIC(8),
-- ora-only -- column188                     NUMERIC(8),
-- ora-only -- column189                     NUMERIC(8),
-- ora-only -- column190                     NUMERIC(8),
-- ora-only -- column191                     NUMERIC(8),
-- ora-only -- column192                     NUMERIC(8),
-- ora-only -- column193                     NUMERIC(8),
-- ora-only -- column194                     NUMERIC(8),
-- ora-only -- column195                     NUMERIC(8),
-- ora-only -- column196                     NUMERIC(8),
-- ora-only -- column197                     NUMERIC(8),
-- ora-only -- column198                     NUMERIC(8),
-- ora-only -- column199                     NUMERIC(8),
-- ora-only -- column200                     NUMERIC(8),
-- ora-only -- column201                     NUMERIC(8),
-- ora-only -- column202                     NUMERIC(8),
-- ora-only -- column203                     NUMERIC(8),
-- ora-only -- column204                     NUMERIC(8),
-- ora-only -- column205                     NUMERIC(8),
-- ora-only -- column206                     NUMERIC(8),
-- ora-only -- column207                     NUMERIC(8),
-- ora-only -- column208                     NUMERIC(8),
-- ora-only -- column209                     NUMERIC(8),
-- ora-only -- column210                     NUMERIC(8),
-- ora-only -- column211                     NUMERIC(8),
-- ora-only -- column212                     NUMERIC(8),
-- ora-only -- column213                     NUMERIC(8),
-- ora-only -- column214                     NUMERIC(8),
-- ora-only -- column215                     NUMERIC(8),
-- ora-only -- column216                     NUMERIC(8),
-- ora-only -- column217                     NUMERIC(8),
-- ora-only -- column218                     NUMERIC(8),
-- ora-only -- column219                     NUMERIC(8),
-- ora-only -- column220                     NUMERIC(8),
-- ora-only -- column221                     NUMERIC(8),
-- ora-only -- column222                     NUMERIC(8),
-- ora-only -- column223                     NUMERIC(8),
-- ora-only -- column224                     NUMERIC(8),
-- ora-only -- column225                     NUMERIC(8),
-- ora-only -- column226                     NUMERIC(8),
-- ora-only -- column227                     NUMERIC(8),
-- ora-only -- column228                     NUMERIC(8),
-- ora-only -- column229                     NUMERIC(8),
-- ora-only -- column230                     NUMERIC(8),
-- ora-only -- column231                     NUMERIC(8),
-- ora-only -- column232                     NUMERIC(8),
-- ora-only -- column233                     NUMERIC(8),
-- ora-only -- column234                     NUMERIC(8),
-- ora-only -- column235                     NUMERIC(8),
-- ora-only -- column236                     NUMERIC(8),
-- ora-only -- column237                     NUMERIC(8),
-- ora-only -- column238                     NUMERIC(8),
-- ora-only -- column239                     NUMERIC(8),
-- ora-only -- column240                     NUMERIC(8),
-- ora-only -- column241                     NUMERIC(8),
-- ora-only -- column242                     NUMERIC(8),
-- ora-only -- column243                     NUMERIC(8),
-- ora-only -- column244                     NUMERIC(8),
-- ora-only -- column245                     NUMERIC(8),
-- ora-only -- column246                     NUMERIC(8),
-- ora-only -- column247                     NUMERIC(8),
-- ora-only -- column248                     NUMERIC(8),
-- ora-only -- column249                     NUMERIC(8),
-- ora-only -- column250                     NUMERIC(8),
-- ora-only -- column251                     NUMERIC(8),
-- ora-only -- column252                     NUMERIC(8),
-- ora-only -- column253                     NUMERIC(8),
-- ora-only -- column254                     NUMERIC(8),
-- ora-only -- column255                     NUMERIC(8),
-- ora-only -- column256                     NUMERIC(8),
-- ora-only -- column257                     NUMERIC(8),
-- ora-only -- column258                     NUMERIC(8),
-- ora-only -- column259                     NUMERIC(8),
-- ora-only -- column260                     NUMERIC(8),
-- ora-only -- column261                     NUMERIC(8),
-- ora-only -- column262                     NUMERIC(8),
-- ora-only -- column263                     NUMERIC(8),
-- ora-only -- column264                     NUMERIC(8),
-- ora-only -- column265                     NUMERIC(8),
-- ora-only -- column266                     NUMERIC(8),
-- ora-only -- column267                     NUMERIC(8),
-- ora-only -- column268                     NUMERIC(8),
-- ora-only -- column269                     NUMERIC(8),
-- ora-only -- column270                     NUMERIC(8),
-- ora-only -- column271                     NUMERIC(8),
-- ora-only -- column272                     NUMERIC(8),
-- ora-only -- column273                     NUMERIC(8),
-- ora-only -- column274                     NUMERIC(8),
-- ora-only -- column275                     NUMERIC(8),
-- ora-only -- column276                     NUMERIC(8),
-- ora-only -- column277                     NUMERIC(8),
-- ora-only -- column278                     NUMERIC(8),
-- ora-only -- column279                     NUMERIC(8),
-- ora-only -- column280                     NUMERIC(8),
-- ora-only -- column281                     NUMERIC(8),
-- ora-only -- column282                     NUMERIC(8),
-- ora-only -- column283                     NUMERIC(8),
-- ora-only -- column284                     NUMERIC(8),
-- ora-only -- column285                     NUMERIC(8),
-- ora-only -- column286                     NUMERIC(8),
-- ora-only -- column287                     NUMERIC(8),
-- ora-only -- column288                     NUMERIC(8),
-- ora-only -- column289                     NUMERIC(8),
-- ora-only -- column290                     NUMERIC(8),
-- ora-only -- column291                     NUMERIC(8),
-- ora-only -- column292                     NUMERIC(8),
-- ora-only -- column293                     NUMERIC(8),
-- ora-only -- column294                     NUMERIC(8),
-- ora-only -- column295                     NUMERIC(8),
-- ora-only -- column296                     NUMERIC(8),
-- ora-only -- column297                     NUMERIC(8),
-- ora-only -- column298                     NUMERIC(8),
-- ora-only -- column299                     NUMERIC(8),
-- ora-only -- column300                     NUMERIC(8),
-- ora-only -- column301                     NUMERIC(8),
-- ora-only -- column302                     NUMERIC(8),
-- ora-only -- column303                     NUMERIC(8),
-- ora-only -- column304                     NUMERIC(8),
-- ora-only -- column305                     NUMERIC(8),
-- ora-only -- column306                     NUMERIC(8),
-- ora-only -- column307                     NUMERIC(8),
-- ora-only -- column308                     NUMERIC(8),
-- ora-only -- column309                     NUMERIC(8),
-- ora-only -- column310                     NUMERIC(8),
-- ora-only -- column311                     NUMERIC(8),
-- ora-only -- column312                     NUMERIC(8),
-- ora-only -- column313                     NUMERIC(8),
-- ora-only -- column314                     NUMERIC(8),
-- ora-only -- column315                     NUMERIC(8),
-- ora-only -- column316                     NUMERIC(8),
-- ora-only -- column317                     NUMERIC(8),
-- ora-only -- column318                     NUMERIC(8),
-- ora-only -- column319                     NUMERIC(8),
-- ora-only -- column320                     NUMERIC(8),
-- ora-only -- column321                     NUMERIC(8),
-- ora-only -- column322                     NUMERIC(8),
-- ora-only -- column323                     NUMERIC(8),
-- ora-only -- column324                     NUMERIC(8),
-- ora-only -- column325                     NUMERIC(8),
-- ora-only -- column326                     NUMERIC(8),
-- ora-only -- column327                     NUMERIC(8),
-- ora-only -- column328                     NUMERIC(8),
-- ora-only -- column329                     NUMERIC(8),
-- ora-only -- column330                     NUMERIC(8),
-- ora-only -- column331                     NUMERIC(8),
-- ora-only -- column332                     NUMERIC(8),
-- ora-only -- column333                     NUMERIC(8),
-- ora-only -- column334                     NUMERIC(8),
-- ora-only -- column335                     NUMERIC(8),
-- ora-only -- column336                     NUMERIC(8),
-- ora-only -- column337                     NUMERIC(8),
-- ora-only -- column338                     NUMERIC(8),
-- ora-only -- column339                     NUMERIC(8),
-- ora-only -- column340                     NUMERIC(8),
-- ora-only -- column341                     NUMERIC(8),
-- ora-only -- column342                     NUMERIC(8),
-- ora-only -- column343                     NUMERIC(8),
-- ora-only -- column344                     NUMERIC(8),
-- ora-only -- column345                     NUMERIC(8),
-- ora-only -- column346                     NUMERIC(8),
-- ora-only -- column347                     NUMERIC(8),
-- ora-only -- column348                     NUMERIC(8),
-- ora-only -- column349                     NUMERIC(8),
-- ora-only -- column350                     NUMERIC(8),
-- ora-only -- column351                     NUMERIC(8),
-- ora-only -- column352                     NUMERIC(8),
-- ora-only -- column353                     NUMERIC(8),
-- ora-only -- column354                     NUMERIC(8),
-- ora-only -- column355                     NUMERIC(8),
-- ora-only -- column356                     NUMERIC(8),
-- ora-only -- column357                     NUMERIC(8),
-- ora-only -- column358                     NUMERIC(8),
-- ora-only -- column359                     NUMERIC(8),
-- ora-only -- column360                     NUMERIC(8),
-- ora-only -- column361                     NUMERIC(8),
-- ora-only -- column362                     NUMERIC(8),
-- ora-only -- column363                     NUMERIC(8),
-- ora-only -- column364                     NUMERIC(8),
-- ora-only -- column365                     NUMERIC(8),
-- ora-only -- column366                     NUMERIC(8),
-- ora-only -- column367                     NUMERIC(8),
-- ora-only -- column368                     NUMERIC(8),
-- ora-only -- column369                     NUMERIC(8),
-- ora-only -- column370                     NUMERIC(8),
-- ora-only -- column371                     NUMERIC(8),
-- ora-only -- column372                     NUMERIC(8),
-- ora-only -- column373                     NUMERIC(8),
-- ora-only -- column374                     NUMERIC(8),
-- ora-only -- column375                     NUMERIC(8),
-- ora-only -- column376                     NUMERIC(8),
-- ora-only -- column377                     NUMERIC(8),
-- ora-only -- column378                     NUMERIC(8),
-- ora-only -- column379                     NUMERIC(8),
-- ora-only -- column380                     NUMERIC(8),
-- ora-only -- column381                     NUMERIC(8),
-- ora-only -- column382                     NUMERIC(8),
-- ora-only -- column383                     NUMERIC(8),
-- ora-only -- column384                     NUMERIC(8),
-- ora-only -- column385                     NUMERIC(8),
-- ora-only -- column386                     NUMERIC(8),
-- ora-only -- column387                     NUMERIC(8),
-- ora-only -- column388                     NUMERIC(8),
-- ora-only -- column389                     NUMERIC(8),
-- ora-only -- column390                     NUMERIC(8),
-- ora-only -- column391                     NUMERIC(8),
-- ora-only -- column392                     NUMERIC(8),
-- ora-only -- column393                     NUMERIC(8),
-- ora-only -- column394                     NUMERIC(8),
-- ora-only -- column395                     NUMERIC(8),
-- ora-only -- column396                     NUMERIC(8),
-- ora-only -- column397                     NUMERIC(8),
-- ora-only -- column398                     NUMERIC(8),
-- ora-only -- column399                     NUMERIC(8),
-- ora-only -- column400                     NUMERIC(8),
-- ora-only -- column401                     NUMERIC(8),
-- ora-only -- column402                     NUMERIC(8),
-- ora-only -- column403                     NUMERIC(8),
-- ora-only -- column404                     NUMERIC(8),
-- ora-only -- column405                     NUMERIC(8),
-- ora-only -- column406                     NUMERIC(8),
-- ora-only -- column407                     NUMERIC(8),
-- ora-only -- column408                     NUMERIC(8),
-- ora-only -- column409                     NUMERIC(8),
-- ora-only -- column410                     NUMERIC(8),
-- ora-only -- column411                     NUMERIC(8),
-- ora-only -- column412                     NUMERIC(8),
-- ora-only -- column413                     NUMERIC(8),
-- ora-only -- column414                     NUMERIC(8),
-- ora-only -- column415                     NUMERIC(8),
-- ora-only -- column416                     NUMERIC(8),
-- ora-only -- column417                     NUMERIC(8),
-- ora-only -- column418                     NUMERIC(8),
-- ora-only -- column419                     NUMERIC(8),
-- ora-only -- column420                     NUMERIC(8),
-- ora-only -- column421                     NUMERIC(8),
-- ora-only -- column422                     NUMERIC(8),
-- ora-only -- column423                     NUMERIC(8),
-- ora-only -- column424                     NUMERIC(8),
-- ora-only -- column425                     NUMERIC(8),
-- ora-only -- column426                     NUMERIC(8),
-- ora-only -- column427                     NUMERIC(8),
-- ora-only -- column428                     NUMERIC(8),
-- ora-only -- column429                     NUMERIC(8),
-- ora-only -- column430                     NUMERIC(8),
-- ora-only -- column431                     NUMERIC(8),
-- ora-only -- column432                     NUMERIC(8),
-- ora-only -- column433                     NUMERIC(8),
-- ora-only -- column434                     NUMERIC(8),
-- ora-only -- column435                     NUMERIC(8),
-- ora-only -- column436                     NUMERIC(8),
-- ora-only -- column437                     NUMERIC(8),
-- ora-only -- column438                     NUMERIC(8),
-- ora-only -- column439                     NUMERIC(8),
-- ora-only -- column440                     NUMERIC(8),
-- ora-only -- column441                     NUMERIC(8),
-- ora-only -- column442                     NUMERIC(8),
-- ora-only -- column443                     NUMERIC(8),
-- ora-only -- column444                     NUMERIC(8),
-- ora-only -- column445                     NUMERIC(8),
-- ora-only -- column446                     NUMERIC(8),
-- ora-only -- column447                     NUMERIC(8),
-- ora-only -- column448                     NUMERIC(8),
-- ora-only -- column449                     NUMERIC(8),
-- ora-only -- column450                     NUMERIC(8),
-- ora-only -- column451                     NUMERIC(8),
-- ora-only -- column452                     NUMERIC(8),
-- ora-only -- column453                     NUMERIC(8),
-- ora-only -- column454                     NUMERIC(8),
-- ora-only -- column455                     NUMERIC(8),
-- ora-only -- column456                     NUMERIC(8),
-- ora-only -- column457                     NUMERIC(8),
-- ora-only -- column458                     NUMERIC(8),
-- ora-only -- column459                     NUMERIC(8),
-- ora-only -- column460                     NUMERIC(8),
-- ora-only -- column461                     NUMERIC(8),
-- ora-only -- column462                     NUMERIC(8),
-- ora-only -- column463                     NUMERIC(8),
-- ora-only -- column464                     NUMERIC(8),
-- ora-only -- column465                     NUMERIC(8),
-- ora-only -- column466                     NUMERIC(8),
-- ora-only -- column467                     NUMERIC(8),
-- ora-only -- column468                     NUMERIC(8),
-- ora-only -- column469                     NUMERIC(8),
-- ora-only -- column470                     NUMERIC(8),
-- ora-only -- column471                     NUMERIC(8),
-- ora-only -- column472                     NUMERIC(8),
-- ora-only -- column473                     NUMERIC(8),
-- ora-only -- column474                     NUMERIC(8),
-- ora-only -- column475                     NUMERIC(8),
-- ora-only -- column476                     NUMERIC(8),
-- ora-only -- column477                     NUMERIC(8),
-- ora-only -- column478                     NUMERIC(8),
-- ora-only -- column479                     NUMERIC(8),
-- ora-only -- column480                     NUMERIC(8),
-- ora-only -- column481                     NUMERIC(8),
-- ora-only -- column482                     NUMERIC(8),
-- ora-only -- column483                     NUMERIC(8),
-- ora-only -- column484                     NUMERIC(8),
-- ora-only -- column485                     NUMERIC(8),
-- ora-only -- column486                     NUMERIC(8),
-- ora-only -- column487                     NUMERIC(8),
-- ora-only -- column488                     NUMERIC(8),
-- ora-only -- column489                     NUMERIC(8),
-- ora-only -- column490                     NUMERIC(8),
-- ora-only -- column491                     NUMERIC(8),
-- ora-only -- column492                     NUMERIC(8),
-- ora-only -- column493                     NUMERIC(8),
-- ora-only -- column494                     NUMERIC(8),
-- ora-only -- column495                     NUMERIC(8),
-- ora-only -- column496                     NUMERIC(8),
-- ora-only -- column497                     NUMERIC(8),
-- ora-only -- column498                     NUMERIC(8),
-- ora-only -- column499                     NUMERIC(8),
-- ora-only -- column500                     NUMERIC(8),
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL
-- ora-only --);
-- ora-only --
-- ora-only --ALTER TABLE apidb.GroupTaxonMatrix
-- ora-only --ADD CONSTRAINT gtm_pk UNIQUE (group_taxon_matrix_id);
-- ora-only --
-- ora-only --ALTER TABLE apidb.GroupTaxonMatrix
-- ora-only --ADD CONSTRAINT gtm_fk1 FOREIGN KEY (ortholog_group_id)
-- ora-only --REFERENCES apidb.OrthologGroup (ortholog_group_id);
-- ora-only --
-- ora-only --CREATE UNIQUE INDEX gtm_group_id 
-- ora-only --    ON apidb.GroupTaxonMatrix (ortholog_group_id);
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE apidb.GroupTaxonMatrix_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --           
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'GroupTaxonMatrix',
-- ora-only --       'Standard', 'GROUP_TAXON_MATRIX_ID',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('GroupTaxonMatrix') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only --                     
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE TABLE apidb.OrthologGroupAaSequence (
-- ora-only -- ortholog_group_aa_sequence_id NUMERIC(12) NOT NULL,
-- ora-only -- ortholog_group_id             NUMERIC(12) NOT NULL,
-- ora-only -- aa_sequence_id                NUMERIC(12) NOT NULL,
-- ora-only -- connectivity                  FLOAT(40),
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL
-- ora-only --);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthologGroupAaSequence
-- ora-only --ADD CONSTRAINT ogas_pk UNIQUE (ortholog_group_aa_sequence_id);
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthologGroupAaSequence
-- ora-only --ADD CONSTRAINT ogas_fk1 FOREIGN KEY (ortholog_group_id)
-- ora-only --REFERENCES apidb.OrthologGroup;
-- ora-only --
-- ora-only --ALTER TABLE apidb.OrthologGroupAaSequence
-- ora-only --ADD CONSTRAINT ogas_fk2 FOREIGN KEY (aa_sequence_id)
-- ora-only --REFERENCES dots.AaSequenceImp;
-- ora-only --
-- ora-only --
-- ora-only --CREATE INDEX ogas_ogas_ix
-- ora-only --ON apidb.OrthologGroupAaSequence (ortholog_group_id, aa_sequence_id);
-- ora-only --
-- ora-only --CREATE INDEX ogas_asog_ix
-- ora-only --ON apidb.OrthologGroupAaSequence (aa_sequence_id, ortholog_group_id);
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE apidb.OrthologGroupAaSequence_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthologGroupAaSequence',
-- ora-only --       'Standard', 'ORTHOLOG_GROUP_AA_SEQUENCE_ID',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthologGroupAaSequence') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE TABLE ApiDB.OrthomclResource (
-- ora-only -- orthomcl_resource_id          NUMERIC(10) NOT NULL,
-- ora-only -- orthomcl_taxon_id             NUMERIC(10) NOT NULL,
-- ora-only -- resource_name                 VARCHAR(50) NOT NULL,
-- ora-only -- resource_url                  VARCHAR(255) NOT NULL,
-- ora-only -- resource_version              VARCHAR(100),
-- ora-only -- strain                        VARCHAR(100),
-- ora-only -- description                   VARCHAR(255),
-- ora-only -- linkout_url                   VARCHAR(255),
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL,
-- ora-only -- FOREIGN KEY (orthomcl_taxon_id) REFERENCES ApiDB.OrthomclTaxon (orthomcl_taxon_id),
-- ora-only -- PRIMARY KEY (orthomcl_resource_id)
-- ora-only --);
-- ora-only --
-- ora-only --CREATE INDEX OrthomclResource_revix
-- ora-only --ON ApiDB.OrthomclResource (orthomcl_taxon_id, orthomcl_resource_id);
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE ApiDB.OrthomclResource_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthomclResource',
-- ora-only --       'Standard', 'orthomcl_resource_id',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthomclResource') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only -----------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE TABLE ApiDB.OrthomclGroupKeyword (
-- ora-only -- orthomcl_keyword_id           NUMERIC(10) NOT NULL,
-- ora-only -- ortholog_group_id             NUMERIC(10) NOT NULL,
-- ora-only -- keyword                       VARCHAR(255) NOT NULL,
-- ora-only -- frequency                     VARCHAR(255) NOT NULL,
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL,
-- ora-only -- FOREIGN KEY (ortholog_group_id) REFERENCES ApiDB.OrthologGroup (ortholog_group_id),
-- ora-only -- PRIMARY KEY (orthomcl_keyword_id)
-- ora-only --);
-- ora-only --
-- ora-only --CREATE INDEX ogk_group_ix ON apidb.OrthomclGroupKeyword(ortholog_group_id);
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE ApiDB.OrthomclGroupKeyword_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthomclGroupKeyword',
-- ora-only --       'Standard', 'orthomcl_keyword_id',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthomclGroupKeyword') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only -----------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE TABLE ApiDB.OrthomclGroupDomain (
-- ora-only -- orthomcl_domain_id           NUMERIC(10) NOT NULL,
-- ora-only -- ortholog_group_id             NUMERIC(10) NOT NULL,
-- ora-only -- description                   VARCHAR(255) NOT NULL,
-- ora-only -- frequency                     FLOAT NOT NULL,
-- ora-only -- modification_date             timestamp NOT NULL,
-- ora-only -- user_read                     NUMERIC(1) NOT NULL,
-- ora-only -- user_write                    NUMERIC(1) NOT NULL,
-- ora-only -- group_read                    NUMERIC(1) NOT NULL,
-- ora-only -- group_write                   NUMERIC(1) NOT NULL,
-- ora-only -- other_read                    NUMERIC(1) NOT NULL,
-- ora-only -- other_write                   NUMERIC(1) NOT NULL,
-- ora-only -- row_user_id                   NUMERIC(12) NOT NULL,
-- ora-only -- row_group_id                  NUMERIC(3) NOT NULL,
-- ora-only -- row_project_id                NUMERIC(4) NOT NULL,
-- ora-only -- row_alg_invocation_id         NUMERIC(12) NOT NULL,
-- ora-only -- FOREIGN KEY (ortholog_group_id) REFERENCES ApiDB.OrthologGroup (ortholog_group_id),
-- ora-only -- PRIMARY KEY (orthomcl_domain_id)
-- ora-only --);
-- ora-only --
-- ora-only --CREATE INDEX ogd_group_ix ON apidb.OrthomclGroupDomain(ortholog_group_id);
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --CREATE SEQUENCE ApiDB.OrthomclGroupDomain_sq;
-- ora-only --
-- ora-only --------------------------------------------------------------------------------
-- ora-only --
-- ora-only --INSERT INTO core.TableInfo
-- ora-only --    (table_id, name, table_type, primary_key_column, database_id, is_versioned,
-- ora-only --     is_view, view_on_table_id, superclass_table_id, is_updatable, 
-- ora-only --     modification_date, user_read, user_write, group_read, group_write, 
-- ora-only --     other_read, other_write, row_user_id, row_group_id, row_project_id, 
-- ora-only --     row_alg_invocation_id)
-- ora-only --SELECT nextval('core.tableinfo_sq'), 'OrthomclGroupDomain',
-- ora-only --       'Standard', 'orthomcl_domain_id',
-- ora-only --       (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'), 0, 0, NULL, NULL, 
-- ora-only --       1,current_timestamp, 1, 1, 1, 1, 1, 1, 1, 1,
-- ora-only --       (SELECT MAX(project_id) AS project_id FROM core.ProjectInfo), 0
-- ora-only --WHERE lower('OrthomclGroupDomain') NOT IN (SELECT lower(name) FROM core.TableInfo
-- ora-only --        WHERE database_id = (SELECT database_id FROM core.DatabaseInfo WHERE lower(name) = 'apidb'));
-- ora-only --
-- ora-only --
-- ora-only ----------------------------------------------------------------------------------
-- ora-only --
