
ALTER TABLE DoTS.Similarity ALTER total_match_length DROP NOT NULL;
ALTER TABLE DoTS.Similarity ALTER NUMERIC_identical DROP NOT NULL;
ALTER TABLE DoTS.Similarity ALTER NUMERIC_positive DROP NOT NULL;
ALTER TABLE DoTS.Similarity ALTER score DROP NOT NULL;
ALTER TABLE DoTS.Similarity ALTER pvalue_mant DROP NOT NULL;
ALTER TABLE DoTS.Similarity ALTER pvalue_exp DROP NOT NULL;

ALTER TABLE DoTS.SimilaritySpan ALTER match_length DROP NOT NULL;
ALTER TABLE DoTS.SimilaritySpan ALTER NUMERIC_identical DROP NOT NULL;
ALTER TABLE DoTS.SimilaritySpan ALTER NUMERIC_positive DROP NOT NULL;
ALTER TABLE DoTS.SimilaritySpan ALTER score DROP NOT NULL;
ALTER TABLE DoTS.SimilaritySpan ALTER pvalue_mant DROP NOT NULL;
ALTER TABLE DoTS.SimilaritySpan ALTER pvalue_exp DROP NOT NULL;

ALTER TABLE DoTSVer.SimilarityVer ALTER total_match_length DROP NOT NULL;
ALTER TABLE DoTSVer.SimilarityVer ALTER NUMERIC_identical DROP NOT NULL;
ALTER TABLE DoTSVer.SimilarityVer ALTER NUMERIC_positive DROP NOT NULL;
ALTER TABLE DoTSVer.SimilarityVer ALTER score DROP NOT NULL;
ALTER TABLE DoTSVer.SimilarityVer ALTER pvalue_mant DROP NOT NULL;
ALTER TABLE DoTSVer.SimilarityVer ALTER pvalue_exp DROP NOT NULL;

ALTER TABLE DoTSVer.SimilaritySpanVer ALTER match_length DROP NOT NULL;
ALTER TABLE DoTSVer.SimilaritySpanVer ALTER NUMERIC_identical DROP NOT NULL;
ALTER TABLE DoTSVer.SimilaritySpanVer ALTER NUMERIC_positive DROP NOT NULL;
ALTER TABLE DoTSVer.SimilaritySpanVer ALTER score DROP NOT NULL;
ALTER TABLE DoTSVer.SimilaritySpanVer ALTER pvalue_mant DROP NOT NULL;
ALTER TABLE DoTSVer.SimilaritySpanVer ALTER pvalue_exp DROP NOT NULL;

