PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT distinct ?entity ?col
WHERE { 
	?entity a owl:Class .
 	?entity obo:EUPATH_0000755 ?column . 
	?entity rdfs:subClassOf* {ENTITY} .
	BIND(str(?column) AS ?col) .
}

