PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT distinct ?cls ?pIRI
WHERE { 
	?cls a owl:Class .
	OPTIONAL {
		?cls rdfs:subClassOf ?p_cls .
	}
	BIND (IF(BOUND(?p_cls), ?p_cls, "Thing") AS ?pIRI) .
}
ORDER BY DESC (?pIRI)