PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?label
WHERE {
  ?entity rdfs:subClassOf <http://www.w3.org/2002/07/owl#Thing> .
  ?entity rdfs:label ?slabel.
  BIND (str(?slabel) AS ?label) .
}

