update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_094260';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_074550';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_013620';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP37 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_094560';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP37 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_074860';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP37 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_013410';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP4 / ROP7 (incomplete catalytic triad) ***WARNING: GENE MODEL INACCURATE ***', modification_date = sysdate where source_id = 'TGME49_095110';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP4 / ROP7 (incomplete catalytic triad) ***WARNING: GENE MODEL INACCURATE ***', modification_date = sysdate where source_id = 'TGGT1_075470';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP4 / ROP7 (incomplete catalytic triad) ***WARNING: GENE MODEL INACCURATE ***', modification_date = sysdate where source_id = 'TGVEG_050030';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP4 / ROP7 (incomplete catalytic triad) ***WARNING: GENE MODEL INACCURATE ***', modification_date = sysdate where source_id = 'TGVEG_050040';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_095760';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_054260';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_050200';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP36 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_007610';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP36 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_020500';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP36 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_040670';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP22 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_007700';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP22 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_040590';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family', modification_date = sysdate where source_id = 'TGME49_007820';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family', modification_date = sysdate where source_id = 'TGGT1_020800';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family', modification_date = sysdate where source_id = 'TGVEG_040370';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_009050';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_021990';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_039410';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP42 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_009980';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP42 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_023030';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP42 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_038540';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP43 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_010090';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP44 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_010110';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP44 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_064740';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP44 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_038530';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_121650';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_064690';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_058800';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family, MEK kinase-related (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_021550';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family, MEK kinase-related (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_065410';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family, MEK kinase-related (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_052210';
update dots.genefeature set label = product, product = 'SCY kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_022960';
update dots.genefeature set label = product, product = 'SCY kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_066500';
update dots.genefeature set label = product, product = 'SCY kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_053380';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_075610';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_000730';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_055650';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP24 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_052360';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP24 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_001270';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP24 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_056070';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_053330';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_002310';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_056600';
update dots.genefeature set label = product, product = 'CMCG kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_053440';
update dots.genefeature set label = product, product = 'CMCG kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_002520';
update dots.genefeature set label = product, product = 'CMCG kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_056710';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family', modification_date = sysdate where source_id = 'TGME49_053580';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family', modification_date = sysdate where source_id = 'TGGT1_002750';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family', modification_date = sysdate where source_id = 'TGVEG_056840';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_053860';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_003020';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_057110';
update dots.genefeature set label = product, product = 'CAM kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_053940';
update dots.genefeature set label = product, product = 'CAM kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_003220';
update dots.genefeature set label = product, product = 'CAM kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_057220';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_054190';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_003580';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_057460';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGME49_054630';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGGT1_004180';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGVEG_057970';
update dots.genefeature set label = product, product = 'SCY kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_120000';
update dots.genefeature set label = product, product = 'SCY kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_121390';
update dots.genefeature set label = product, product = 'SCY kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_011100';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_119700';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_121590';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_010900';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_119610';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_121680';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_010810';
update dots.genefeature set label = product, product = 'Aurora kinase(incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_118770';
update dots.genefeature set label = product, product = 'Aurora kinase(incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_122340';
update dots.genefeature set label = product, product = 'Aurora kinase(incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_010150';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP26 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_011260';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP26 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_123660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP26 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_009140';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1', modification_date = sysdate where source_id = 'TGME49_101440';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1', modification_date = sysdate where source_id = 'TGGT1_059880';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1', modification_date = sysdate where source_id = 'TGVEG_042030';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_101270';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_059690';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_042170';
update dots.genefeature set label = product, product = 'CAM Kinase, RAD family', modification_date = sysdate where source_id = 'TGME49_037860';
update dots.genefeature set label = product, product = 'CAM Kinase, RAD family', modification_date = sysdate where source_id = 'TGGT1_058410';
update dots.genefeature set label = product, product = 'CAM Kinase, RAD family', modification_date = sysdate where source_id = 'TGVEG_041720';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_037890';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_058370';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_041690';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_012970';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_039780';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_035260';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_086470';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_037890';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_033700';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_083790';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_035810';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_032130';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGME49_083480';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGGT1_035500';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGVEG_031910';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_039130';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_051830';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_092380';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_039380';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_051500';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_092230';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_039420';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_051450';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_092180';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_039440';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_051430';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_092160';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP23 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_039600';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP23 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_051260';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP23 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_091990';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_039900';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_050920';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_091660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP34, putative', modification_date = sysdate where source_id = 'TGME49_040090';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP34, putative', modification_date = sysdate where source_id = 'TGGT1_050750';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP34, putative', modification_date = sysdate where source_id = 'TGVEG_091480';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_040390';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_050480';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_040410';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_050460';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_090890';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_040420';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_050450';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_090880';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGME49_040630';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGGT1_050250';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGVEG_090670';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1a', modification_date = sysdate where source_id = 'TGME49_040640';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1a', modification_date = sysdate where source_id = 'TGGT1_050240';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1a', modification_date = sysdate where source_id = 'TGVEG_090660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP38', modification_date = sysdate where source_id = 'TGME49_042110';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP38', modification_date = sysdate where source_id = 'TGGT1_048210';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP29', modification_date = sysdate where source_id = 'TGME49_042230';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP19', modification_date = sysdate where source_id = 'TGME49_042240';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP19', modification_date = sysdate where source_id = 'TGME49_042250';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP19', modification_date = sysdate where source_id = 'TGGT1_047790';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_042400';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_047420';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_102490';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_043340';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_046520';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_103210';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1/AMK1 family ToxPK1', modification_date = sysdate where source_id = 'TGME49_043500';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1/AMK1 family ToxPK1', modification_date = sysdate where source_id = 'TGGT1_046360';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1/AMK1 family ToxPK1', modification_date = sysdate where source_id = 'TGVEG_103370';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_044620';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_045210';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_104420';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP35', modification_date = sysdate where source_id = 'TGME49_104740';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP35', modification_date = sysdate where source_id = 'TGGT1_006790';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP35', modification_date = sysdate where source_id = 'TGVEG_041270';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_006590';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_062170';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_000240';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_005550';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_063360';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_043720';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP18', modification_date = sysdate where source_id = 'TGME49_005250';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP18', modification_date = sysdate where source_id = 'TGGT1_063760';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGME49_004280';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGGT1_016430';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGVEG_044960';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGME49_004100';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGGT1_016600';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGVEG_045110';
update dots.genefeature set label = product, product = 'Aurora kinase', modification_date = sysdate where source_id = 'TGME49_003010';
update dots.genefeature set label = product, product = 'Aurora kinase', modification_date = sysdate where source_id = 'TGGT1_017920';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP25', modification_date = sysdate where source_id = 'TGME49_002780';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP25', modification_date = sysdate where source_id = 'TGGT1_018170';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP25', modification_date = sysdate where source_id = 'TGVEG_046570';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP33, putative', modification_date = sysdate where source_id = 'TGME49_001130';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP33, putative', modification_date = sysdate where source_id = 'TGGT1_020190';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP33, putative', modification_date = sysdate where source_id = 'TGVEG_048170';
update dots.genefeature set label = product, product = 'protein kinase, PfPK7 homolog', modification_date = sysdate where source_id = 'TGME49_081430';
update dots.genefeature set label = product, product = 'protein kinase, PfPK7 homolog', modification_date = sysdate where source_id = 'TGGT1_006020';
update dots.genefeature set label = product, product = 'protein kinase, PfPK7 homolog', modification_date = sysdate where source_id = 'TGVEG_088420';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_081450';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_005900';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_088440';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP45 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_081790';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP45 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_005680';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP45 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_088660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP21', modification_date = sysdate where source_id = 'TGME49_063220';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP21', modification_date = sysdate where source_id = 'TGGT1_043320';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP21', modification_date = sysdate where source_id = 'TGVEG_049690';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGME49_063070';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGGT1_043160';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGVEG_049920';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP16', modification_date = sysdate where source_id = 'TGME49_062730';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP16', modification_date = sysdate where source_id = 'TGGT1_007360';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP16', modification_date = sysdate where source_id = 'TGVEG_071990';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGME49_062540';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGGT1_007560';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGVEG_072200';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP39', modification_date = sysdate where source_id = 'TGME49_062050';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP39', modification_date = sysdate where source_id = 'TGGT1_008060';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP39', modification_date = sysdate where source_id = 'TGVEG_072800';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_060030';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_010090';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_074240';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP31', modification_date = sysdate where source_id = 'TGME49_058800';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP31', modification_date = sysdate where source_id = 'TGGT1_011370';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP31', modification_date = sysdate where source_id = 'TGVEG_075660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP17', modification_date = sysdate where source_id = 'TGME49_058580';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP17', modification_date = sysdate where source_id = 'TGGT1_011620';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP17', modification_date = sysdate where source_id = 'TGVEG_075890';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP28', modification_date = sysdate where source_id = 'TGME49_058370';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP28', modification_date = sysdate where source_id = 'TGGT1_011840';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP28', modification_date = sysdate where source_id = 'TGVEG_076100';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP20', modification_date = sysdate where source_id = 'TGME49_058230';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP20', modification_date = sysdate where source_id = 'TGGT1_011980';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP20', modification_date = sysdate where source_id = 'TGVEG_076240';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGME49_058010';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGGT1_012190';
update dots.genefeature set label = product, product = 'CAM kinase', modification_date = sysdate where source_id = 'TGVEG_076530';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_056890';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_013860';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_077570';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGME49_056070';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGGT1_014160';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGVEG_078090';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGME49_055710';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGGT1_077220';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGVEG_078350';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGME49_029020';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGGT1_118720';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGVEG_026470';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_029630';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_118140';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_025870';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP46, putative', modification_date = sysdate where source_id = 'TGME49_030470';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP46, putative', modification_date = sysdate where source_id = 'TGGT1_117490';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP46, putative', modification_date = sysdate where source_id = 'TGVEG_025110';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_031070';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_116650';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_024510';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family TgMAPK2', modification_date = sysdate where source_id = 'TGME49_033010';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family TgMAPK2', modification_date = sysdate where source_id = 'TGGT1_114510';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family TgMAPK2', modification_date = sysdate where source_id = 'TGVEG_022640';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_033790';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_113550';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_021730';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGME49_033900';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGGT1_113440';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGVEG_021620';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_074170';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_113350';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_021530';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGME49_073690';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGGT1_112770';
update dots.genefeature set label = product, product = 'Wee kinase', modification_date = sysdate where source_id = 'TGVEG_020930';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_072540';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_111830';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_020060';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_072470';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_111760';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_019990';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_072200';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_111410';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_019680';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP32', modification_date = sysdate where source_id = 'TGME49_070920';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP32', modification_date = sysdate where source_id = 'TGGT1_109770';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_070330';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_108860';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_017630';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_069730';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_108160';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_016960';
update dots.genefeature set label = product, product = 'protein kinase, PfEST homolog', modification_date = sysdate where source_id = 'TGME49_068010';
update dots.genefeature set label = product, product = 'protein kinase, PfEST homolog', modification_date = sysdate where source_id = 'TGGT1_106200';
update dots.genefeature set label = product, product = 'protein kinase, PfEST homolog', modification_date = sysdate where source_id = 'TGVEG_015140';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_068210';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_106280';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_015230';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_067540';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_109040';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_066950';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_076000';
update dots.genefeature set label = product, product = 'Atypical MEK-related kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_085940';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGME49_066910';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGGT1_076050';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGVEG_086090';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_066780';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_076190';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_086230';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_066710';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_076260';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_086300';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP41', modification_date = sysdate where source_id = 'TGME49_066100';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP41', modification_date = sysdate where source_id = 'TGGT1_056660';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP41', modification_date = sysdate where source_id = 'TGVEG_080460';
update dots.genefeature set label = product, product = 'CMGC kinase, GSK family TgPK3', modification_date = sysdate where source_id = 'TGME49_065330';
update dots.genefeature set label = product, product = 'CMGC kinase, GSK family TgPK3', modification_date = sysdate where source_id = 'TGGT1_057780';
update dots.genefeature set label = product, product = 'CMGC kinase, GSK family TgPK3', modification_date = sysdate where source_id = 'TGVEG_081010';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_088440';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_034950';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_082200';
update dots.genefeature set label = product, product = 'FIK kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_089050';
update dots.genefeature set label = product, product = 'FIK kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_034200';
update dots.genefeature set label = product, product = 'FIK kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_034210';
update dots.genefeature set label = product, product = 'FIK kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_082930';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1b', modification_date = sysdate where source_id = 'TGME49_089320';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1b', modification_date = sysdate where source_id = 'TGGT1_033900';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1) TgCK1b', modification_date = sysdate where source_id = 'TGVEG_083180';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGME49_091050';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGGT1_032070';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGVEG_084460';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP40 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_091960';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP40 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_031600';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP40 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_084990';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_092060';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_031500';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_085090';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_092140';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_031430';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_085270';
update dots.genefeature set label = product, product = 'PEK kinase', modification_date = sysdate where source_id = 'TGME49_010280';
update dots.genefeature set label = product, product = 'PEK kinase', modification_date = sysdate where source_id = 'TGGT1_053320';
update dots.genefeature set label = product, product = 'PEK kinase', modification_date = sysdate where source_id = 'TGVEG_106020';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGME49_107640';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGGT1_054930';
update dots.genefeature set label = product, product = 'CMGC kinase, CK2 family', modification_date = sysdate where source_id = 'TGVEG_029740';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgPK1', modification_date = sysdate where source_id = 'TGME49_104970';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgPK1', modification_date = sysdate where source_id = 'TGGT1_042520';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgPK1', modification_date = sysdate where source_id = 'TGVEG_106290';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1_2 (TGTPK4)', modification_date = sysdate where source_id = 'TGME49_105860';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1_2 (TGTPK4)', modification_date = sysdate where source_id = 'TGGT1_041610';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family TgCDPK1_2 (TGTPK4)', modification_date = sysdate where source_id = 'TGVEG_107290';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGME49_106480';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGGT1_040860';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family', modification_date = sysdate where source_id = 'TGVEG_107940';
update dots.genefeature set label = product, product = 'CAM kinase, RAD family ', modification_date = sysdate where source_id = 'TGME49_028750';
update dots.genefeature set label = product, product = 'CAM kinase, RAD family ', modification_date = sysdate where source_id = 'TGGT1_084330';
update dots.genefeature set label = product, product = 'CAM kinase, RAD family ', modification_date = sysdate where source_id = 'TGVEG_069410';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_028420';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_083990';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_069190';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP11 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_027810';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP11 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_083110';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP11 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_068600';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP30', modification_date = sysdate where source_id = 'TGME49_027010';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP30', modification_date = sysdate where source_id = 'TGGT1_082500';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP30', modification_date = sysdate where source_id = 'TGVEG_068030';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_026540';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_081690';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_067600';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGME49_026030';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGGT1_081170';
update dots.genefeature set label = product, product = 'AGC kinase', modification_date = sysdate where source_id = 'TGVEG_066990';
update dots.genefeature set label = product, product = 'STE kinase', modification_date = sysdate where source_id = 'TGME49_025960';
update dots.genefeature set label = product, product = 'STE kinase', modification_date = sysdate where source_id = 'TGGT1_081110';
update dots.genefeature set label = product, product = 'STE kinase', modification_date = sysdate where source_id = 'TGVEG_066930';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_025770';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_080900';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_066750';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgPK6', modification_date = sysdate where source_id = 'TGME49_025490';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgPK6', modification_date = sysdate where source_id = 'TGGT1_080700';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgPK6', modification_date = sysdate where source_id = 'TGVEG_066560';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgTOXPK2', modification_date = sysdate where source_id = 'TGME49_024950';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgTOXPK2', modification_date = sysdate where source_id = 'TGGT1_079870';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family  TgTOXPK2', modification_date = sysdate where source_id = 'TGVEG_065800';
update dots.genefeature set label = product, product = 'CMGC kinase, Lammer family ', modification_date = sysdate where source_id = 'TGME49_024480';
update dots.genefeature set label = product, product = 'CMGC kinase, Lammer family ', modification_date = sysdate where source_id = 'TGGT1_079100';
update dots.genefeature set label = product, product = 'CMGC kinase, Lammer family ', modification_date = sysdate where source_id = 'TGVEG_065160';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_034950';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_034970';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_071150';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_062280';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGME49_035370';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGGT1_070620';
update dots.genefeature set label = product, product = 'protein kinase', modification_date = sysdate where source_id = 'TGVEG_062010';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGME49_035750';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGGT1_070020';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGVEG_061530';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_036240';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_069520';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_061080';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_036620';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_069220';
update dots.genefeature set label = product, product = 'protein kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_060700';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGME49_037210';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGGT1_068710';
update dots.genefeature set label = product, product = 'Tyrosine kinase-like (TKL) protein', modification_date = sysdate where source_id = 'TGVEG_060030';
update dots.genefeature set label = product, product = 'AGC kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_015670';
update dots.genefeature set label = product, product = 'AGC kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_126590';
update dots.genefeature set label = product, product = 'AGC kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_030140';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP8 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_015770';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP8 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_126670';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP8 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_030050';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP2A (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_015780';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP2A (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_030040';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP2B (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_075300';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_110190';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_086420';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_094270';
update dots.genefeature set label = product, product = 'AGC kinase TgPKG1', modification_date = sysdate where source_id = 'TGME49_111360';
update dots.genefeature set label = product, product = 'AGC kinase TgPKG1', modification_date = sysdate where source_id = 'TGGT1_087710';
update dots.genefeature set label = product, product = 'AGC kinase TgPKG1', modification_date = sysdate where source_id = 'TGVEG_095470';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_111510';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_087870';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_095630';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family (ERK) TgMAPK-1', modification_date = sysdate where source_id = 'TGME49_112570';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family (ERK) TgMAPK-1', modification_date = sysdate where source_id = 'TGGT1_088860';
update dots.genefeature set label = product, product = 'CMGC kinase, MAPK family (ERK) TgMAPK-1', modification_date = sysdate where source_id = 'TGVEG_096690';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGME49_113180';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGGT1_089470';
update dots.genefeature set label = product, product = 'CMGC kinase, Dyrk family ', modification_date = sysdate where source_id = 'TGVEG_097210';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP27', modification_date = sysdate where source_id = 'TGME49_113330';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP27', modification_date = sysdate where source_id = 'TGGT1_089730';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP27', modification_date = sysdate where source_id = 'TGVEG_097390';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGME49_115190';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGGT1_092620';
update dots.genefeature set label = product, product = 'CAM kinase, SNF1 family ', modification_date = sysdate where source_id = 'TGVEG_100200';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGME49_116150';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGGT1_093860';
update dots.genefeature set label = product, product = 'ULK kinase', modification_date = sysdate where source_id = 'TGVEG_101260';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP5 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_108080';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP5 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_042710';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein ROP5 (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_069980';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family ', modification_date = sysdate where source_id = 'TGME49_018720';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family ', modification_date = sysdate where source_id = 'TGGT1_029570';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family ', modification_date = sysdate where source_id = 'TGGT1_029680';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family ', modification_date = sysdate where source_id = 'TGVEG_071120';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein ', modification_date = sysdate where source_id = 'TGME49_018550';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein ', modification_date = sysdate where source_id = 'TGGT1_029380';
update dots.genefeature set label = product, product = 'PIK3R4 kinase-related protein ', modification_date = sysdate where source_id = 'TGVEG_071190';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGME49_018400';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGGT1_029220';
update dots.genefeature set label = product, product = 'NEK kinase', modification_date = sysdate where source_id = 'TGVEG_071340';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family TgPK2', modification_date = sysdate where source_id = 'TGME49_018220';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family TgPK2', modification_date = sysdate where source_id = 'TGGT1_028940';
update dots.genefeature set label = product, product = 'CMGC kinase, CDK family TgPK2', modification_date = sysdate where source_id = 'TGVEG_071520';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family CAM kinase TgTPK5', modification_date = sysdate where source_id = 'TGME49_017600';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family CAM kinase TgTPK5', modification_date = sysdate where source_id = 'TGGT1_028460';
update dots.genefeature set label = product, product = 'CAM kinase, CDPK family CAM kinase TgTPK5', modification_date = sysdate where source_id = 'TGVEG_006910';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1)', modification_date = sysdate where source_id = 'TGME49_047710';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1)', modification_date = sysdate where source_id = 'TGGT1_025100';
update dots.genefeature set label = product, product = 'Casein kinase one (CK1)', modification_date = sysdate where source_id = 'TGVEG_004080';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGME49_049260';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGGT1_100840';
update dots.genefeature set label = product, product = 'CMGC kinase', modification_date = sysdate where source_id = 'TGVEG_002610';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_049470';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_101120';
update dots.genefeature set label = product, product = 'Rhoptry kinase family protein, truncated (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_002390';
update dots.genefeature set label = product, product = 'TBC domain-containing kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGME49_050680';
update dots.genefeature set label = product, product = 'TBC domain-containing kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGGT1_102110';
update dots.genefeature set label = product, product = 'TBC domain-containing kinase (incomplete catalytic triad)', modification_date = sysdate where source_id = 'TGVEG_001420';
update dots.genefeature set label = product, product = 'CMGC kinase, putative', modification_date = sysdate where source_id = 'TGME49_050850';
update dots.genefeature set label = product, product = 'CMGC kinase, putative', modification_date = sysdate where source_id = 'TGGT1_102410';
update dots.genefeature set label = product, product = 'protein kinase, BUD32 homolog', modification_date = sysdate where source_id = 'TGME49_078900';
update dots.genefeature set label = product, product = 'protein kinase, BUD32 homolog', modification_date = sysdate where source_id = 'TGGT1_103460';
update dots.genefeature set label = product, product = 'protein kinase, BUD32 homolog', modification_date = sysdate where source_id = 'TGVEG_029520';
commit;
quit;
