update dots.genefeature set label = product, product = 'SRS10', modification_date = sysdate where source_id = 'TGME49_095600';
update dots.genefeature set label = product, product = 'SRS10', modification_date = sysdate where source_id = 'TGGT1_054430';
update dots.genefeature set label = product, product = 'SRS10', modification_date = sysdate where source_id = 'TGVEG_050370';
update dots.genefeature set label = product, product = 'SRS11 (= SAG2B)', modification_date = sysdate where source_id = 'TGME49_008850';
update dots.genefeature set label = product, product = 'SRS11 (= SAG2B)', modification_date = sysdate where source_id = 'TGGT1_021880';
update dots.genefeature set label = product, product = 'SRS11 (= SAG2B)', modification_date = sysdate where source_id = 'TGVEG_039520';
update dots.genefeature set label = product, product = 'SRS12A', modification_date = sysdate where source_id = 'TGME49_121490';
update dots.genefeature set label = product, product = 'SRS12A', modification_date = sysdate where source_id = 'TGGT1_064540';
update dots.genefeature set label = product, product = 'SRS12A', modification_date = sysdate where source_id = 'TGVEG_059040';
update dots.genefeature set label = product, product = 'SRS12B', modification_date = sysdate where source_id = 'TGME49_121480';
update dots.genefeature set label = product, product = 'SRS12B', modification_date = sysdate where source_id = 'TGGT1_064530';
update dots.genefeature set label = product, product = 'SRS12B', modification_date = sysdate where source_id = 'TGVEG_059050';
update dots.genefeature set label = product, product = 'SRS12D', modification_date = sysdate where source_id = 'TGME49_121470';
update dots.genefeature set label = product, product = 'SRS12D', modification_date = sysdate where source_id = 'TGGT1_064520';
update dots.genefeature set label = product, product = 'SRS12D', modification_date = sysdate where source_id = 'TGVEG_059060';
update dots.genefeature set label = product, product = 'SRS13', modification_date = sysdate where source_id = 'TGME49_022370';
update dots.genefeature set label = product, product = 'SRS13', modification_date = sysdate where source_id = 'TGGT1_066180';
update dots.genefeature set label = product, product = 'SRS14', modification_date = sysdate where source_id = 'TGME49_054060';
update dots.genefeature set label = product, product = 'SRS14', modification_date = sysdate where source_id = 'TGGT1_003340';
update dots.genefeature set label = product, product = 'SRS14', modification_date = sysdate where source_id = 'TGVEG_057320';
update dots.genefeature set label = product, product = 'SRS15A', modification_date = sysdate where source_id = 'TGME49_120250';
update dots.genefeature set label = product, product = 'SRS15A', modification_date = sysdate where source_id = 'TGGT1_121040';
update dots.genefeature set label = product, product = 'SRS15B', modification_date = sysdate where source_id = 'TGME49_120240';
update dots.genefeature set label = product, product = 'SRS15B', modification_date = sysdate where source_id = 'TGGT1_121050';
update dots.genefeature set label = product, product = 'SRS15C', modification_date = sysdate where source_id = 'TGME49_120230';
update dots.genefeature set label = product, product = 'SRS15C', modification_date = sysdate where source_id = 'TGGT1_121060';
update dots.genefeature set label = product, product = 'SRS16A', modification_date = sysdate where source_id = 'TGME49_120200';
update dots.genefeature set label = product, product = 'SRS16A', modification_date = sysdate where source_id = 'TGGT1_121090';
update dots.genefeature set label = product, product = 'SRS16A', modification_date = sysdate where source_id = 'TGVEG_011380';
update dots.genefeature set label = product, product = 'SRS16B (= SRS9)', modification_date = sysdate where source_id = 'TGME49_120190';
update dots.genefeature set label = product, product = 'SRS16B (= SRS9)', modification_date = sysdate where source_id = 'TGGT1_121100';
update dots.genefeature set label = product, product = 'SRS16C (= BSR4, P36)', modification_date = sysdate where source_id = 'TGME49_120180';
update dots.genefeature set label = product, product = 'SRS16C (= BSR4, P36)', modification_date = sysdate where source_id = 'TGGT1_121110';
update dots.genefeature set label = product, product = 'SRS16E (= SRS6)', modification_date = sysdate where source_id = 'TGME49_120170';
update dots.genefeature set label = product, product = 'SRS16E (= SRS6)', modification_date = sysdate where source_id = 'TGGT1_121120';
update dots.genefeature set label = product, product = 'SRS16E (= SRS6)', modification_date = sysdate where source_id = 'TGVEG_011260';
update dots.genefeature set label = product, product = 'SRS17', modification_date = sysdate where source_id = 'TGME49_119360';
update dots.genefeature set label = product, product = 'SRS17', modification_date = sysdate where source_id = 'TGGT1_121840';
update dots.genefeature set label = product, product = 'SRS17', modification_date = sysdate where source_id = 'TGVEG_010670';
update dots.genefeature set label = product, product = 'SRS19A', modification_date = sysdate where source_id = 'TGME49_101140';
update dots.genefeature set label = product, product = 'SRS19A', modification_date = sysdate where source_id = 'TGGT1_059560';
update dots.genefeature set label = product, product = 'SRS19A', modification_date = sysdate where source_id = 'TGVEG_042300';
update dots.genefeature set label = product, product = 'SRS19B (= SRS 8)', modification_date = sysdate where source_id = 'TGME49_101150';
update dots.genefeature set label = product, product = 'SRS19B (= SRS 8)', modification_date = sysdate where source_id = 'TGGT1_059570';
update dots.genefeature set label = product, product = 'SRS19B (= SRS 8)', modification_date = sysdate where source_id = 'TGVEG_042290';
update dots.genefeature set label = product, product = 'SRS19C (= SRS7)', modification_date = sysdate where source_id = 'TGME49_101160';
update dots.genefeature set label = product, product = 'SRS19C (= SRS7)', modification_date = sysdate where source_id = 'TGGT1_059580';
update dots.genefeature set label = product, product = 'SRS19C (= SRS7)', modification_date = sysdate where source_id = 'TGVEG_042280';
update dots.genefeature set label = product, product = 'SRS19D', modification_date = sysdate where source_id = 'TGME49_101170';
update dots.genefeature set label = product, product = 'SRS19D', modification_date = sysdate where source_id = 'TGGT1_059590';
update dots.genefeature set label = product, product = 'SRS19D', modification_date = sysdate where source_id = 'TGVEG_042270';
update dots.genefeature set label = product, product = 'SRS19F', modification_date = sysdate where source_id = 'TGME49_101180';
update dots.genefeature set label = product, product = 'SRS19F', modification_date = sysdate where source_id = 'TGGT1_059600';
update dots.genefeature set label = product, product = 'SRS19F', modification_date = sysdate where source_id = 'TGVEG_042260';
update dots.genefeature set label = product, product = 'SRS20A', modification_date = sysdate where source_id = 'TGME49_085870';
update dots.genefeature set label = product, product = 'SRS20A', modification_date = sysdate where source_id = 'TGGT1_037270';
update dots.genefeature set label = product, product = 'SRS20A', modification_date = sysdate where source_id = 'TGVEG_033260';
update dots.genefeature set label = product, product = 'SRS20C', modification_date = sysdate where source_id = 'TGME49_085860';
update dots.genefeature set label = product, product = 'SRS20C', modification_date = sysdate where source_id = 'TGGT1_037260';
update dots.genefeature set label = product, product = 'SRS20C', modification_date = sysdate where source_id = 'TGVEG_033250';
update dots.genefeature set label = product, product = 'SRS21', modification_date = sysdate where source_id = 'TGME49_083460';
update dots.genefeature set label = product, product = 'SRS21', modification_date = sysdate where source_id = 'TGGT1_035480';
update dots.genefeature set label = product, product = 'SRS21', modification_date = sysdate where source_id = 'TGVEG_031900';
update dots.genefeature set label = product, product = 'SRS22A', modification_date = sysdate where source_id = 'TGME49_038440';
update dots.genefeature set label = product, product = 'SRS22A', modification_date = sysdate where source_id = 'TGGT1_052490';
update dots.genefeature set label = product, product = 'SRS22A', modification_date = sysdate where source_id = 'TGVEG_036210';
update dots.genefeature set label = product, product = 'SRS22B', modification_date = sysdate where source_id = 'TGME49_038460';
update dots.genefeature set label = product, product = 'SRS22B', modification_date = sysdate where source_id = 'TGGT1_052480';
update dots.genefeature set label = product, product = 'SRS22B', modification_date = sysdate where source_id = 'TGVEG_036230';
update dots.genefeature set label = product, product = 'SRS22C', modification_date = sysdate where source_id = 'TGME49_038470';
update dots.genefeature set label = product, product = 'SRS22C', modification_date = sysdate where source_id = 'TGGT1_052470';
update dots.genefeature set label = product, product = 'SRS22C', modification_date = sysdate where source_id = 'TGVEG_036240';
update dots.genefeature set label = product, product = 'SRS22D', modification_date = sysdate where source_id = 'TGME49_038480';
update dots.genefeature set label = product, product = 'SRS22D', modification_date = sysdate where source_id = 'TGGT1_052460';
update dots.genefeature set label = product, product = 'SRS22D', modification_date = sysdate where source_id = 'TGVEG_036250';
update dots.genefeature set label = product, product = 'SRS22E', modification_date = sysdate where source_id = 'TGME49_038490';
update dots.genefeature set label = product, product = 'SRS22E', modification_date = sysdate where source_id = 'TGVEG_036260';
update dots.genefeature set label = product, product = 'SRS22F', modification_date = sysdate where source_id = 'TGME49_038500';
update dots.genefeature set label = product, product = 'SRS22F', modification_date = sysdate where source_id = 'TGVEG_036270';
update dots.genefeature set label = product, product = 'SRS22G', modification_date = sysdate where source_id = 'TGME49_038520';
update dots.genefeature set label = product, product = 'SRS22G', modification_date = sysdate where source_id = 'TGVEG_036290';
update dots.genefeature set label = product, product = 'SRS22H', modification_date = sysdate where source_id = 'TGME49_038630';
update dots.genefeature set label = product, product = 'SRS22H', modification_date = sysdate where source_id = 'TGVEG_036320';
update dots.genefeature set label = product, product = 'SRS22I', modification_date = sysdate where source_id = 'TGME49_038850';
update dots.genefeature set label = product, product = 'SRS22I', modification_date = sysdate where source_id = 'TGVEG_092770';
update dots.genefeature set label = product, product = 'SRS23', modification_date = sysdate where source_id = 'TGME49_039090';
update dots.genefeature set label = product, product = 'SRS23', modification_date = sysdate where source_id = 'TGVEG_092420';
update dots.genefeature set label = product, product = 'SRS26A', modification_date = sysdate where source_id = 'TGME49_059410';
update dots.genefeature set label = product, product = 'SRS26A', modification_date = sysdate where source_id = 'TGGT1_010510';
update dots.genefeature set label = product, product = 'SRS26A', modification_date = sysdate where source_id = 'TGVEG_074740';
update dots.genefeature set label = product, product = 'SRS26B', modification_date = sysdate where source_id = 'TGME49_059300';
update dots.genefeature set label = product, product = 'SRS26C', modification_date = sysdate where source_id = 'TGME49_059290';
update dots.genefeature set label = product, product = 'SRS26C', modification_date = sysdate where source_id = 'TGGT1_010520';
update dots.genefeature set label = product, product = 'SRS26C', modification_date = sysdate where source_id = 'TGVEG_074950';
update dots.genefeature set label = product, product = 'SRS26E', modification_date = sysdate where source_id = 'TGME49_059270';
update dots.genefeature set label = product, product = 'SRS26E', modification_date = sysdate where source_id = 'TGGT1_010540';
update dots.genefeature set label = product, product = 'SRS26E', modification_date = sysdate where source_id = 'TGVEG_074970';
update dots.genefeature set label = product, product = 'SRS27B', modification_date = sysdate where source_id = 'TGME49_058810';
update dots.genefeature set label = product, product = 'SRS27B', modification_date = sysdate where source_id = 'TGGT1_011360';
update dots.genefeature set label = product, product = 'SRS27B', modification_date = sysdate where source_id = 'TGVEG_075650';
update dots.genefeature set label = product, product = 'SRS28 (= SporoSAG)', modification_date = sysdate where source_id = 'TGME49_058550';
update dots.genefeature set label = product, product = 'SRS28 (= SporoSAG)', modification_date = sysdate where source_id = 'TGGT1_011650';
update dots.genefeature set label = product, product = 'SRS28 (= SporoSAG)', modification_date = sysdate where source_id = 'TGVEG_075920';
update dots.genefeature set label = product, product = 'SRS29A (= SRS1)', modification_date = sysdate where source_id = 'TGME49_033450';
update dots.genefeature set label = product, product = 'SRS29A (= SRS1)', modification_date = sysdate where source_id = 'TGGT1_114020';
update dots.genefeature set label = product, product = 'SRS29A (= SRS1)', modification_date = sysdate where source_id = 'TGVEG_022090';
update dots.genefeature set label = product, product = 'SRS29B (= SAG1, P30)', modification_date = sysdate where source_id = 'TGME49_033460';
update dots.genefeature set label = product, product = 'SRS29B (= SAG1, P30)', modification_date = sysdate where source_id = 'TGGT1_114010';
update dots.genefeature set label = product, product = 'SRS29B (= SAG1, P30)', modification_date = sysdate where source_id = 'TGVEG_022080';
update dots.genefeature set label = product, product = 'SRS29C (= SRS2, P35)', modification_date = sysdate where source_id = 'TGME49_033480';
update dots.genefeature set label = product, product = 'SRS29C (= SRS2, P35)', modification_date = sysdate where source_id = 'TGGT1_113990';
update dots.genefeature set label = product, product = 'SRS29C (= SRS2, P35)', modification_date = sysdate where source_id = 'TGVEG_022060';
update dots.genefeature set label = product, product = 'SRS30A', modification_date = sysdate where source_id = 'TGME49_073130';
update dots.genefeature set label = product, product = 'SRS30A', modification_date = sysdate where source_id = 'TGGT1_112300';
update dots.genefeature set label = product, product = 'SRS30C', modification_date = sysdate where source_id = 'TGME49_073120';
update dots.genefeature set label = product, product = 'SRS30C', modification_date = sysdate where source_id = 'TGVEG_020430';
update dots.genefeature set label = product, product = 'SRS30D', modification_date = sysdate where source_id = 'TGME49_073110';
update dots.genefeature set label = product, product = 'SRS30D', modification_date = sysdate where source_id = 'TGGT1_112290';
update dots.genefeature set label = product, product = 'SRS30D', modification_date = sysdate where source_id = 'TGVEG_020420';
update dots.genefeature set label = product, product = 'SRS31C', modification_date = sysdate where source_id = 'TGME49_072560';
update dots.genefeature set label = product, product = 'SRS31C', modification_date = sysdate where source_id = 'TGGT1_111850';
update dots.genefeature set label = product, product = 'SRS31C', modification_date = sysdate where source_id = 'TGVEG_020080';
update dots.genefeature set label = product, product = 'SRS32', modification_date = sysdate where source_id = 'TGME49_071980';
update dots.genefeature set label = product, product = 'SRS32', modification_date = sysdate where source_id = 'TGGT1_110990';
update dots.genefeature set label = product, product = 'SRS32', modification_date = sysdate where source_id = 'TGVEG_019440';
update dots.genefeature set label = product, product = 'SRS33', modification_date = sysdate where source_id = 'TGME49_071130';
update dots.genefeature set label = product, product = 'SRS33', modification_date = sysdate where source_id = 'TGGT1_110010';
update dots.genefeature set label = product, product = 'SRS33', modification_date = sysdate where source_id = 'TGVEG_018410';
update dots.genefeature set label = product, product = 'SRS34A (= SAG2A, P22)', modification_date = sysdate where source_id = 'TGME49_071050';
update dots.genefeature set label = product, product = 'SRS34A (= SAG2A, P22)', modification_date = sysdate where source_id = 'TGGT1_109930';
update dots.genefeature set label = product, product = 'SRS34A (= SAG2A, P22)', modification_date = sysdate where source_id = 'TGVEG_018330';
update dots.genefeature set label = product, product = 'SRS34B', modification_date = sysdate where source_id = 'TGME49_071040';
update dots.genefeature set label = product, product = 'SRS34B', modification_date = sysdate where source_id = 'TGGT1_109920';
update dots.genefeature set label = product, product = 'SRS34B', modification_date = sysdate where source_id = 'TGVEG_018320';
update dots.genefeature set label = product, product = 'SRS38D', modification_date = sysdate where source_id = 'TGME49_067160';
update dots.genefeature set label = product, product = 'SRS38C', modification_date = sysdate where source_id = 'TGME49_067150';
update dots.genefeature set label = product, product = 'SRS38C', modification_date = sysdate where source_id = 'TGGT1_075780';
update dots.genefeature set label = product, product = 'SRS38C', modification_date = sysdate where source_id = 'TGVEG_085750';
update dots.genefeature set label = product, product = 'SRS38B', modification_date = sysdate where source_id = 'TGME49_067140';
update dots.genefeature set label = product, product = 'SRS38A', modification_date = sysdate where source_id = 'TGME49_067130';
update dots.genefeature set label = product, product = 'SRS38A', modification_date = sysdate where source_id = 'TGGT1_075790';
update dots.genefeature set label = product, product = 'SRS38A', modification_date = sysdate where source_id = 'TGVEG_085760';
update dots.genefeature set label = product, product = 'SRS36A', modification_date = sysdate where source_id = 'TGME49_092250';
update dots.genefeature set label = product, product = 'SRS36A', modification_date = sysdate where source_id = 'TGGT1_031310';
update dots.genefeature set label = product, product = 'SRS36B (= SAG5D)', modification_date = sysdate where source_id = 'TGME49_092260';
update dots.genefeature set label = product, product = 'SRS36C (= SAG5A)', modification_date = sysdate where source_id = 'TGME49_092270';
update dots.genefeature set label = product, product = 'SRS36C (= SAG5A)', modification_date = sysdate where source_id = 'TGGT1_031300';
update dots.genefeature set label = product, product = 'SRS36C (= SAG5A)', modification_date = sysdate where source_id = 'TGVEG_085460';
update dots.genefeature set label = product, product = 'SRS36D (= SAG5C)', modification_date = sysdate where source_id = 'TGME49_092280';
update dots.genefeature set label = product, product = 'SRS36D (= SAG5C)', modification_date = sysdate where source_id = 'TGGT1_031290';
update dots.genefeature set label = product, product = 'SRS37A', modification_date = sysdate where source_id = 'TGME49_010320';
update dots.genefeature set label = product, product = 'SRS37A', modification_date = sysdate where source_id = 'TGVEG_105970';
update dots.genefeature set label = product, product = 'SRS37B', modification_date = sysdate where source_id = 'TGME49_010330';
update dots.genefeature set label = product, product = 'SRS37B', modification_date = sysdate where source_id = 'TGVEG_105960';
update dots.genefeature set label = product, product = 'SRS40A', modification_date = sysdate where source_id = 'TGME49_024790';
update dots.genefeature set label = product, product = 'SRS40A', modification_date = sysdate where source_id = 'TGVEG_065640';
update dots.genefeature set label = product, product = 'SRS40D', modification_date = sysdate where source_id = 'TGME49_024770';
update dots.genefeature set label = product, product = 'SRS40E (= SRS4)', modification_date = sysdate where source_id = 'TGME49_024760';
update dots.genefeature set label = product, product = 'SRS40E (= SRS4)', modification_date = sysdate where source_id = 'TGGT1_079680';
update dots.genefeature set label = product, product = 'SRS40E (= SRS4)', modification_date = sysdate where source_id = 'TGVEG_065630';
update dots.genefeature set label = product, product = 'SRS40F', modification_date = sysdate where source_id = 'TGME49_024750';
update dots.genefeature set label = product, product = 'SRS40F', modification_date = sysdate where source_id = 'TGGT1_079670';
update dots.genefeature set label = product, product = 'SRS42', modification_date = sysdate where source_id = 'TGME49_034370';
update dots.genefeature set label = product, product = 'SRS42', modification_date = sysdate where source_id = 'TGGT1_071520';
update dots.genefeature set label = product, product = 'SRS42', modification_date = sysdate where source_id = 'TGVEG_062740';
update dots.genefeature set label = product, product = 'SRS43', modification_date = sysdate where source_id = 'TGME49_034930';
update dots.genefeature set label = product, product = 'SRS43', modification_date = sysdate where source_id = 'TGGT1_071180';
update dots.genefeature set label = product, product = 'SRS43', modification_date = sysdate where source_id = 'TGVEG_062310';
update dots.genefeature set label = product, product = 'SRS45', modification_date = sysdate where source_id = 'TGME49_035600';
update dots.genefeature set label = product, product = 'SRS45', modification_date = sysdate where source_id = 'TGGT1_070180';
update dots.genefeature set label = product, product = 'SRS45', modification_date = sysdate where source_id = 'TGVEG_061780';
update dots.genefeature set label = product, product = 'SRS46', modification_date = sysdate where source_id = 'TGME49_014190';
update dots.genefeature set label = product, product = 'SRS46', modification_date = sysdate where source_id = 'TGGT1_124500';
update dots.genefeature set label = product, product = 'SRS46', modification_date = sysdate where source_id = 'TGVEG_031670';
update dots.genefeature set label = product, product = 'SRS47A', modification_date = sysdate where source_id = 'TGME49_015670';
update dots.genefeature set label = product, product = 'SRS47A', modification_date = sysdate where source_id = 'TGGT1_126590';
update dots.genefeature set label = product, product = 'SRS47A', modification_date = sysdate where source_id = 'TGVEG_030140';
update dots.genefeature set label = product, product = 'SRS47B (= SAG2E)', modification_date = sysdate where source_id = 'TGME49_015680';
update dots.genefeature set label = product, product = 'SRS47B (= SAG2E)', modification_date = sysdate where source_id = 'TGGT1_126600';
update dots.genefeature set label = product, product = 'SRS47B (= SAG2E)', modification_date = sysdate where source_id = 'TGVEG_030130';
update dots.genefeature set label = product, product = 'SRS47D', modification_date = sysdate where source_id = 'TGME49_075360';
update dots.genefeature set label = product, product = 'SRS47D', modification_date = sysdate where source_id = 'TGGT1_068140';
update dots.genefeature set label = product, product = 'SRS47E', modification_date = sysdate where source_id = 'TGME49_075370';
update dots.genefeature set label = product, product = 'SRS47E', modification_date = sysdate where source_id = 'TGGT1_068130';
update dots.genefeature set label = product, product = 'SRS47F', modification_date = sysdate where source_id = 'TGME49_075380';
update dots.genefeature set label = product, product = 'SRS47F', modification_date = sysdate where source_id = 'TGGT1_068120, TGGT1_068150';
update dots.genefeature set label = product, product = 'SRS47F', modification_date = sysdate where source_id = 'TGVEG_036480';
update dots.genefeature set label = product, product = 'SRS48E', modification_date = sysdate where source_id = 'TGME49_007010';
update dots.genefeature set label = product, product = 'SRS49A (= SAG2Y)', modification_date = sysdate where source_id = 'TGME49_007130';
update dots.genefeature set label = product, product = 'SRS49A (= SAG2Y)', modification_date = sysdate where source_id = 'TGGT1_023370';
update dots.genefeature set label = product, product = 'SRS49A (= SAG2Y)', modification_date = sysdate where source_id = 'TGVEG_036810';
update dots.genefeature set label = product, product = 'SRS49B (= SAG2X)', modification_date = sysdate where source_id = 'TGME49_007140';
update dots.genefeature set label = product, product = 'SRS49B (= SAG2X)', modification_date = sysdate where source_id = 'TGGT1_023380';
update dots.genefeature set label = product, product = 'SRS49B (= SAG2X)', modification_date = sysdate where source_id = 'TGVEG_036820';
update dots.genefeature set label = product, product = 'SRS49C (= SAG2D)', modification_date = sysdate where source_id = 'TGME49_007150';
update dots.genefeature set label = product, product = 'SRS49C (= SAG2D)', modification_date = sysdate where source_id = 'TGGT1_023390';
update dots.genefeature set label = product, product = 'SRS49C (= SAG2D)', modification_date = sysdate where source_id = 'TGVEG_036830';
update dots.genefeature set label = product, product = 'SRS49D (= SAG2C)', modification_date = sysdate where source_id = 'TGME49_007160';
update dots.genefeature set label = product, product = 'SRS49D (= SAG2C)', modification_date = sysdate where source_id = 'TGGT1_023400';
update dots.genefeature set label = product, product = 'SRS49D (= SAG2C)', modification_date = sysdate where source_id = 'TGVEG_036840';
update dots.genefeature set label = product, product = 'SRS51 (= SRS3)', modification_date = sysdate where source_id = 'TGME49_108840';
update dots.genefeature set label = product, product = 'SRS51 (= SRS3)', modification_date = sysdate where source_id = 'TGGT1_055870';
update dots.genefeature set label = product, product = 'SRS51 (= SRS3)', modification_date = sysdate where source_id = 'TGVEG_092940';
update dots.genefeature set label = product, product = 'SRS55A', modification_date = sysdate where source_id = 'TGME49_109300';
update dots.genefeature set label = product, product = 'SRS55A', modification_date = sysdate where source_id = 'TGGT1_056440';
update dots.genefeature set label = product, product = 'SRS55A', modification_date = sysdate where source_id = 'TGVEG_093440';
update dots.genefeature set label = product, product = 'SRS55C', modification_date = sysdate where source_id = 'TGME49_109310';
update dots.genefeature set label = product, product = 'SRS55C', modification_date = sysdate where source_id = 'TGVEG_093450';
update dots.genefeature set label = product, product = 'SRS50', modification_date = sysdate where source_id = 'TGME49_111440';
update dots.genefeature set label = product, product = 'SRS50', modification_date = sysdate where source_id = 'TGGT1_087790';
update dots.genefeature set label = product, product = 'SRS50', modification_date = sysdate where source_id = 'TGVEG_095550';
update dots.genefeature set label = product, product = 'SRS52A', modification_date = sysdate where source_id = 'TGME49_115320';
update dots.genefeature set label = product, product = 'SRS52A', modification_date = sysdate where source_id = 'TGGT1_092760';
update dots.genefeature set label = product, product = 'SRS52A', modification_date = sysdate where source_id = 'TGVEG_100430';
update dots.genefeature set label = product, product = 'SRS52C', modification_date = sysdate where source_id = 'TGME49_115340';
update dots.genefeature set label = product, product = 'SRS52C', modification_date = sysdate where source_id = 'TGVEG_100460';
update dots.genefeature set label = product, product = 'SRS53A', modification_date = sysdate where source_id = 'TGME49_115370';
update dots.genefeature set label = product, product = 'SRS53A', modification_date = sysdate where source_id = 'TGGT1_092820';
update dots.genefeature set label = product, product = 'SRS53A', modification_date = sysdate where source_id = 'TGVEG_100490';
update dots.genefeature set label = product, product = 'SRS53B', modification_date = sysdate where source_id = 'TGME49_115380';
update dots.genefeature set label = product, product = 'SRS53B', modification_date = sysdate where source_id = 'TGGT1_092830';
update dots.genefeature set label = product, product = 'SRS53B', modification_date = sysdate where source_id = 'TGVEG_100500';
update dots.genefeature set label = product, product = 'SRS53C', modification_date = sysdate where source_id = 'TGME49_115390';
update dots.genefeature set label = product, product = 'SRS53C', modification_date = sysdate where source_id = 'TGGT1_092840';
update dots.genefeature set label = product, product = 'SRS53C', modification_date = sysdate where source_id = 'TGVEG_100510';
update dots.genefeature set label = product, product = 'SRS53D', modification_date = sysdate where source_id = 'TGME49_115400';
update dots.genefeature set label = product, product = 'SRS53D', modification_date = sysdate where source_id = 'TGGT1_092850';
update dots.genefeature set label = product, product = 'SRS53D', modification_date = sysdate where source_id = 'TGVEG_100520';
update dots.genefeature set label = product, product = 'SRS53F', modification_date = sysdate where source_id = 'TGME49_115410';
update dots.genefeature set label = product, product = 'SRS53F', modification_date = sysdate where source_id = 'TGGT1_092860';
update dots.genefeature set label = product, product = 'SRS53F', modification_date = sysdate where source_id = 'TGVEG_100530';
update dots.genefeature set label = product, product = 'SRS54', modification_date = sysdate where source_id = 'TGME49_115740';
update dots.genefeature set label = product, product = 'SRS54', modification_date = sysdate where source_id = 'TGGT1_093430';
update dots.genefeature set label = product, product = 'SRS54', modification_date = sysdate where source_id = 'TGVEG_100870';
update dots.genefeature set label = product, product = 'SRS57 (= SAG3, P43)', modification_date = sysdate where source_id = 'TGME49_108020';
update dots.genefeature set label = product, product = 'SRS57 (= SAG3, P43)', modification_date = sysdate where source_id = 'TGGT1_042790';
update dots.genefeature set label = product, product = 'SRS57 (= SAG3, P43)', modification_date = sysdate where source_id = 'TGVEG_069910';
update dots.genefeature set label = product, product = 'SRS56A', modification_date = sysdate where source_id = 'TGME49_046070';
update dots.genefeature set label = product, product = 'SRS56A', modification_date = sysdate where source_id = 'TGGT1_026990';
update dots.genefeature set label = product, product = 'SRS56A', modification_date = sysdate where source_id = 'TGVEG_005730';
update dots.genefeature set label = product, product = 'SRS59A', modification_date = sysdate where source_id = 'TGME49_051960';
update dots.genefeature set label = product, product = 'SRS59A', modification_date = sysdate where source_id = 'TGGT1_103340';
update dots.genefeature set label = product, product = 'SRS59A', modification_date = sysdate where source_id = 'TGVEG_000380';
update dots.genefeature set label = product, product = 'SRS59B', modification_date = sysdate where source_id = 'TGME49_051960';
update dots.genefeature set label = product, product = 'SRS59B', modification_date = sysdate where source_id = 'TGGT1_103340';
update dots.genefeature set label = product, product = 'SRS59B', modification_date = sysdate where source_id = 'TGVEG_000380';
commit;
quit;

