PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT * {
	{
		SELECT distinct ?entity ?col ?dataset
		WHERE { 
			?entity a owl:Class .
		 	?entity obo:EUPATH_0000755 ?column . 
			?entity rdfs:subClassOf* {ENTITY} .
		 	?entity obo:TEMP_0023101 ?_dataset . 
			BIND(str(?column) AS ?col) .
			BIND(str(?_dataset) AS ?dataset) .
		}
	}
	UNION
	{
		SELECT distinct ?entity ?col ?dataset
		WHERE { 
			?entity a owl:Class .
		 	?entity obo:EUPATH_0000755 ?column . 
			?entity rdfs:subClassOf* {ENTITY} .
		 	FILTER NOT EXISTS {
				?entity obo:TEMP_0023101 ?dataset . 
			}
			BIND(str(?column) AS ?col) .
		}
	}
}

