PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT * {
	{
    SELECT distinct ?entity ?parent ?type ?label
    WHERE { 
    	?entity a owl:Class .
      ?entity obo:EUPATH_0001005 ?stype. 
      ?entity rdfs:label ?slabel. 
    	?entity rdfs:subClassOf ?parent_entity .
    	BIND (IF(BOUND(?parent_entity), ?parent_entity, "") AS ?parent) .
    	BIND (IF(BOUND(?slabel),str(?slabel), "") AS ?label) .
    	BIND (IF(BOUND(?type),str(?stype),"variable") AS ?type) .
    }
  }
  UNION
  {
    SELECT distinct ?entity ?parent ?type ?label
    WHERE { 
    	?entity a owl:Class .
      filter not exists {
        ?entity obo:EUPATH_0001005 ?stype  .
      }  
      ?entity rdfs:label ?slabel . 
    	BIND (IF(BOUND(?parent_entity), ?parent_entity, "") AS ?parent) .
    	BIND (IF(BOUND(?slabel),str(?slabel), "") AS ?label) .
    	BIND (str("TYPE NOT SET") AS ?type) .
    }
  }
}
