PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT * {
	{
		SELECT distinct ?entity ?mf
		WHERE { 
			?entity a owl:Class .
  		?entity obo:EUPATH_0001005 ?smf . 
			BIND (str(?smf) AS ?mf ) .
			VALUES ?mf { "yes" } .
		}
	}
}

