PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ebi: <http://www.ebi.ac.uk/efo/>
PREFIX sno: <http://purl.bioontology.org/ontology/SNOMEDCT/>


select ?iri ?label
where {
  ?catleaf a owl:Class .
  ?catleaf rdfs:label ?_label . 
  $catleaf obo:EUPATH_0001005 ?_type .
  BIND (str(?_label) AS ?label) .
  BIND (str(?_type) AS ?type) .
  VALUES ?type  { "multifilter" "category" "" } .
  filter not exists {
    select distinct ?catleaf
      where {
      ?a_entity a owl:Class .
      ?a_entity rdfs:subClassOf ?catleaf .
      }
    } .
  BIND (str(?catleaf) AS ?entity) .
  BIND(
    replace(
      replace(
        replace($entity, str(obo:), ""),
        str(ebi:), ""),
      str(sno:), "SNOMEDCT_")
    as $iri) .
  }
