PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT distinct ?entity ?vars
WHERE { 
	?entity a owl:Class .
        ?entity obo:EUPATH_0000755 ?column. 
	BIND (str(?column) AS ?vars) .
}