PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ebi: <http://www.ebi.ac.uk/efo/>
PREFIX sno: <http://purl.bioontology.org/ontology/SNOMEDCT/>

SELECT * {
  {
    SELECT distinct ?entity ?iri ?vars ?omType ?parent 
    WHERE { 
    	?_entity a owl:Class .
      ?_entity obo:EUPATH_0000755 ?column. 
      ?_entity obo:ISA_1 ?_omType.
      ?_entity obo:ISA_2 ?_parent.
    	BIND (str(?_entity) AS ?entity) .
    	BIND (str(?_omType) AS ?omType) .
    	BIND (str(?_parent) AS ?parent) .
    	BIND (str(?column) AS ?vars) .
      BIND(
        replace(
          replace(
            replace($entity, str(obo:), ""),
            str(ebi:), ""),
          str(sno:), "SNOMEDCT_")
        as $iri) .
    }
  }
UNION
  {
    SELECT distinct ?entity ?iri ?vars
    WHERE { 
    	?_entity a owl:Class .
          filter not exists { 
          ?_entity obo:ISA_2 ?_parent. 
          }
      ?_entity obo:EUPATH_0000755 ?column. 
    	BIND (str(?_entity) AS ?entity) .
    	BIND (str(?column) AS ?vars) .
      BIND(
        replace(
          replace(
            replace($entity, str(obo:), ""),
            str(ebi:), ""),
          str(sno:), "SNOMEDCT_")
        as $iri) .
    }
  }
}
